In [11]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [12]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [21]:
df_train

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15715707.0,P'eng,685.0,France,Female,31.0,4.0,152582.2,1.0,1.0,1.0,130795.52,0.0
1,15651022.0,Ch'ien,590.0,France,Male,43.0,2.0,0.0,2.0,1.0,0.0,96929.24,0.0
2,15589969.0,Yeh,588.0,France,Male,31.0,10.0,0.0,2.0,1.0,1.0,177896.92,0.0
3,15618661.0,Ch'ien,593.0,Spain,Male,37.0,9.0,0.0,2.0,1.0,0.0,53817.23,0.0
4,15771580.0,Nweke,730.0,France,Female,52.0,8.0,0.0,1.0,1.0,0.0,1276.87,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,15700946.0,Chidubem,567.0,France,Female,29.0,6.0,0.0,2.0,1.0,0.0,69409.37,0.0
14996,15652084.0,Teng,476.0,Spain,Male,29.0,3.0,0.0,2.0,1.0,0.0,116973.48,0.0
14997,15657829.0,H?,773.0,France,Male,50.0,4.0,0.0,2.0,1.0,1.0,124071.71,0.0
14998,15781598.0,Ch'en,648.0,France,Male,37.0,3.0,0.0,2.0,1.0,1.0,81602.02,0.0
14999,15777772.0,Chinomso,635.0,France,Male,30.0,1.0,0.0,2.0,1.0,0.0,132959.33,0.0

In [22]:
df_test

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,15628308.0,Nkemjika,583.0,France,Male,40.0,7.0,0.00,2.0,1.0,0.0,151481.86
1,15686909.0,Chiu,595.0,France,Male,39.0,3.0,0.00,2.0,1.0,0.0,87400.53
2,15579616.0,Folliero,622.0,France,Male,24.0,3.0,0.00,2.0,1.0,0.0,176712.59
3,15795953.0,Chukwubuikem,577.0,Germany,Male,50.0,5.0,127305.50,1.0,1.0,1.0,28806.32
4,15752731.0,Y?an,605.0,Spain,Male,39.0,2.0,88915.85,1.0,1.0,0.0,138521.02
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15725002.0,Chukwufumnanya,695.0,France,Female,26.0,7.0,0.00,2.0,1.0,0.0,161807.84
9996,15612092.0,Ijendu,754.0,Spain,Female,28.0,8.0,0.00,2.0,1.0,1.0,109626.01
9997,15750055.0,Ts'ai,676.0,Germany,Male,37.0,3.0,117594.41,2.0,1.0,0.0,176692.87
9998,15789563.0,Macleod,614.0,Spain,Male,38.0,2.0,0.00,2.0,1.0,0.0,124592.83
9999,15642655.0,T'ien,684.0,France,Male,32.0,3.0,0.00,2.0,1.0,0.0,66580.13

In [37]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       15000 non-null  float64
 1   CreditScore      15000 non-null  float64
 2   Geography        15000 non-null  int64
 3   Gender           15000 non-null  int64
 4   Age              15000 non-null  float64
 5   Tenure           15000 non-null  float64
 6   Balance          15000 non-null  float64
 7   NumOfProducts    15000 non-null  float64
 8   HasCrCard        15000 non-null  float64
 9   IsActiveMember   15000 non-null  float64
 10  EstimatedSalary  15000 non-null  float64
 11  Exited           15000 non-null  float64
dtypes: float64(10), int64(2)
memory usage: 1.4 MB

In [38]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10000 non-null  float64
 1   CreditScore      10000 non-null  float64
 2   Geography        10000 non-null  int64
 3   Gender           10000 non-null  int64
 4   Age              10000 non-null  float64
 5   Tenure           10000 non-null  float64
 6   Balance          10000 non-null  float64
 7   NumOfProducts    10000 non-null  float64
 8   HasCrCard        10000 non-null  float64
 9   IsActiveMember   10000 non-null  float64
 10  EstimatedSalary  10000 non-null  float64
dtypes: float64(9), int64(2)
memory usage: 859.5 KB

In [17]:
df_train.isna().sum()

id                 0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [18]:
df_test.isna().sum()

id                 0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
dtype: int64

In [19]:
df_train = df_train.drop('id', axis=1)
df_test = df_test.drop('id', axis=1)

In [29]:
df_train = df_train.drop('Surname', axis=1)
df_test = df_test.drop('Surname', axis=1)

In [30]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [33]:
set(df_test['Geography']).difference(set(df_train['Geography']))

set()

In [34]:
df_train['Geography'] = label.fit_transform(df_train['Geography'])
df_test['Geography'] = label.transform(df_test['Geography'])

In [36]:
df_train['Gender'] = label.fit_transform(df_train['Gender'])
df_test['Gender'] = label.transform(df_test['Gender'])

In [40]:
y_train = df_train['Exited']
X_train = df_train.drop(columns=['Exited'])
X_test = df_test.copy()

In [46]:
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

In [47]:
model = XGBClassifier(
    objective='binary:logistic',
    random_state=42,
    eval_metric='logloss'
)
pipe = Pipeline([('model', model)])

In [48]:
params = {
    "model__n_estimators": [200, 400, 500],
    "model__learning_rate": [0.01, 0.05, 0.1],
    "model__max_depth": [3, 5, 8]
}

In [49]:
final_model = GridSearchCV(pipe, params, cv=3, verbose=2, n_jobs=-1)
final_model.fit(X_train, y_train)

Fitting 3 folds for each of 27 candidates, totalling 81 fits

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('model',
                                        XGBClassifier(base_score=None,
                                                      booster=None,
                                                      callbacks=None,
                                                      colsample_bylevel=None,
                                                      colsample_bynode=None,
                                                      colsample_bytree=None,
                                                      device=None,
                                                      early_stopping_rounds=None,
                                                      enable_categorical=False,
                                                      eval_metric='logloss',
                                                      feature_types=None,
                                                      feature_weights=None,
                                                      gamma=None,
                                                      grow_policy=None,
                                                      importance_type=No...
                                                      max_cat_to_onehot=None,
                                                      max_delta_step=None,
                                                      max_depth=None,
                                                      max_leaves=None,
                                                      min_child_weight=None,
                                                      missing=nan,
                                                      monotone_constraints=None,
                                                      multi_strategy=None,
                                                      n_estimators=None,
                                                      n_jobs=None,
                                                      num_parallel_tree=None, ...))]),
             n_jobs=-1,
             param_grid={'model__learning_rate': [0.01, 0.05, 0.1],
                         'model__max_depth': [3, 5, 8],
                         'model__n_estimators': [200, 400, 500]},
             verbose=2)

In [50]:
y_pred = final_model.predict(X_test)

In [52]:
df_sub = pd.read_csv('sample_submission.csv')

In [53]:
df_sub['Exited'] = y_pred

In [54]:
df_sub.to_csv('sub.csv',index=False,index_label=False)

In [55]:
df_sub

         id  Exited
0     15000       0
1     15001       0
2     15002       0
3     15003       1
4     15004       0
...     ...     ...
9995  24995       0
9996  24996       0
9997  24997       0
9998  24998       0
9999  24999       0

[10000 rows x 2 columns]