In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [3]:
df_train

,event_id,num_perimeters_0_5h,dt_first_last_0_5h,low_temporal_resolution_0_5h,area_first_ha,area_growth_abs_0_5h,area_growth_rel_0_5h,area_growth_rate_ha_per_h,log1p_area_first,log1p_growth,...,dist_fit_r2_0_5h,alignment_cos,alignment_abs,cross_track_component,along_track_speed,event_start_hour,event_start_dayofweek,event_start_month,time_to_hit_hours,event
0,10892457,3,4.265188,0,79.696304,2.875935,0.036086,0.674281,4.390693,1.354787,...,0.886373,-0.054649,0.054649,-1.937219,-0.106026,19,4,5,18.892512,0
1,11757157,2,1.169918,0,8.946749,0.000000,0.000000,0.000000,2.297246,0.000000,...,0.000000,-0.568898,0.568898,-0.000000,-0.000000,4,4,6,22.048108,1
2,11945086,4,4.777526,0,106.482638,0.000000,0.000000,0.000000,4.677329,0.000000,...,0.000000,0.882385,0.882385,0.000000,0.000000,22,4,8,0.888895,1
3,12044083,1,0.000000,1,67.631125,0.000000,0.000000,0.000000,4.228746,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,20,5,8,60.953021,0
4,12052347,2,4.975273,0,35.632874,0.000000,0.000000,0.000000,3.600946,0.000000,...,0.000000,0.934634,0.934634,-0.000000,0.000000,21,5,7,44.990274,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,97075632,1,0.000000,1,51.295195,0.000000,0.000000,0.000000,3.956904,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,17,6,6,66.340624,0
217,97362560,2,1.127102,0,1.176991,0.000000,0.000000,0.000000,0.777943,0.000000,...,0.000000,-0.277779,0.277779,-0.000000,-0.000000,18,1,7,5.694898,1
218,97805715,2,3.710653,0,71.946930,0.000000,0.000000,0.000000,4.289732,0.000000,...,0.000000,0.694609,0.694609,0.000000,0.000000,18,1,9,44.011253,0
219,99071478,1,0.000000,1,20.223659,0.000000,0.000000,0.000000,3.055117,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,15,0,8,22.975783,1
220,99339733,1,0.000000,1,902.231688,0.000000,0.000000,0.000000,6.805979,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,21,1,7,0.617344,0

In [4]:
df_test

,event_id,num_perimeters_0_5h,dt_first_last_0_5h,low_temporal_resolution_0_5h,area_first_ha,area_growth_abs_0_5h,area_growth_rel_0_5h,area_growth_rate_ha_per_h,log1p_area_first,log1p_growth,...,projected_advance_m,dist_accel_m_per_h2,dist_fit_r2_0_5h,alignment_cos,alignment_abs,cross_track_component,along_track_speed,event_start_hour,event_start_dayofweek,event_start_month
0,10662602,1,0.000000,1,2.452217,0.000000,0.00000,0.000000,1.239017,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,3,7
1,13353600,1,0.000000,1,131.669588,0.000000,0.00000,0.000000,4.887862,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,22,0,8
2,13942327,1,0.000000,1,6.723104,0.000000,0.00000,0.000000,2.044216,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,6,7
3,16112781,1,0.000000,1,285.416736,0.000000,0.00000,0.000000,5.657448,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,1,7
4,17132808,7,3.459331,0,61.098604,12.516633,0.20486,3.618224,4.128724,2.603921,...,13.54413,-22.687575,0.044572,0.158550,0.158550,-24.414806,3.920562,23,5,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,94627327,2,4.614923,0,24.438326,0.000000,0.00000,0.000000,3.236257,0.000000,...,0.00000,0.000000,0.000000,0.763809,0.763809,0.000000,0.000000,22,0,6
91,96570675,1,0.000000,1,155.843418,0.000000,0.00000,0.000000,5.055248,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21,2,7
92,97225766,1,0.000000,1,87.761553,0.000000,0.00000,0.000000,4.485954,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4,1,7
93,98446281,2,4.335964,0,11.391108,0.000000,0.00000,0.000000,2.516979,0.000000,...,0.00000,0.000000,0.000000,-0.305683,0.305683,0.000000,-0.000000,17,0,9
94,99649465,1,0.000000,1,15.522466,0.000000,0.00000,0.000000,2.804721,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,22,2,7

In [41]:
test_ids = df_test['event_id'].copy()

In [5]:
drop_cols = ['event', 'time_to_hit_hours', 'event_id']

X_train = df_train.drop(columns=drop_cols)
y_train = df_train['event']

X_test = df_test.drop(columns=drop_cols, errors='ignore')

In [6]:
df_train.isna().sum()

event_id                        0
num_perimeters_0_5h             0
dt_first_last_0_5h              0
low_temporal_resolution_0_5h    0
area_first_ha                   0
area_growth_abs_0_5h            0
area_growth_rel_0_5h            0
area_growth_rate_ha_per_h       0
log1p_area_first                0
log1p_growth                    0
log_area_ratio_0_5h             0
relative_growth_0_5h            0
radial_growth_m                 0
radial_growth_rate_m_per_h      0
centroid_displacement_m         0
centroid_speed_m_per_h          0
spread_bearing_deg              0
spread_bearing_sin              0
spread_bearing_cos              0
dist_min_ci_0_5h                0
dist_std_ci_0_5h                0
dist_change_ci_0_5h             0
dist_slope_ci_0_5h              0
closing_speed_m_per_h           0
closing_speed_abs_m_per_h       0
projected_advance_m             0
dist_accel_m_per_h2             0
dist_fit_r2_0_5h                0
alignment_cos                   0
alignment_abs                   0
cross_track_component           0
along_track_speed               0
event_start_hour                0
event_start_dayofweek           0
event_start_month               0
time_to_hit_hours               0
event                           0
dtype: int64

In [7]:
df_test.isna().sum()

event_id                        0
num_perimeters_0_5h             0
dt_first_last_0_5h              0
low_temporal_resolution_0_5h    0
area_first_ha                   0
area_growth_abs_0_5h            0
area_growth_rel_0_5h            0
area_growth_rate_ha_per_h       0
log1p_area_first                0
log1p_growth                    0
log_area_ratio_0_5h             0
relative_growth_0_5h            0
radial_growth_m                 0
radial_growth_rate_m_per_h      0
centroid_displacement_m         0
centroid_speed_m_per_h          0
spread_bearing_deg              0
spread_bearing_sin              0
spread_bearing_cos              0
dist_min_ci_0_5h                0
dist_std_ci_0_5h                0
dist_change_ci_0_5h             0
dist_slope_ci_0_5h              0
closing_speed_m_per_h           0
closing_speed_abs_m_per_h       0
projected_advance_m             0
dist_accel_m_per_h2             0
dist_fit_r2_0_5h                0
alignment_cos                   0
alignment_abs                   0
cross_track_component           0
along_track_speed               0
event_start_hour                0
event_start_dayofweek           0
event_start_month               0
dtype: int64

In [8]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221 entries, 0 to 220
Data columns (total 37 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   event_id                      221 non-null    int64
 1   num_perimeters_0_5h           221 non-null    int64
 2   dt_first_last_0_5h            221 non-null    float64
 3   low_temporal_resolution_0_5h  221 non-null    int64
 4   area_first_ha                 221 non-null    float64
 5   area_growth_abs_0_5h          221 non-null    float64
 6   area_growth_rel_0_5h          221 non-null    float64
 7   area_growth_rate_ha_per_h     221 non-null    float64
 8   log1p_area_first              221 non-null    float64
 9   log1p_growth                  221 non-null    float64
 10  log_area_ratio_0_5h           221 non-null    float64
 11  relative_growth_0_5h          221 non-null    float64
 12  radial_growth_m               221 non-null    float64
 13  radial_growth_rate_m_per_h    221 non-null    float64
 14  centroid_displacement_m       221 non-null    float64
 15  centroid_speed_m_per_h        221 non-null    float64
 16  spread_bearing_deg            221 non-null    float64
 17  spread_bearing_sin            221 non-null    float64
 18  spread_bearing_cos            221 non-null    float64
 19  dist_min_ci_0_5h              221 non-null    float64
 20  dist_std_ci_0_5h              221 non-null    float64
 21  dist_change_ci_0_5h           221 non-null    float64
 22  dist_slope_ci_0_5h            221 non-null    float64
 23  closing_speed_m_per_h         221 non-null    float64
 24  closing_speed_abs_m_per_h     221 non-null    float64
 25  projected_advance_m           221 non-null    float64
 26  dist_accel_m_per_h2           221 non-null    float64
 27  dist_fit_r2_0_5h              221 non-null    float64
 28  alignment_cos                 221 non-null    float64
 29  alignment_abs                 221 non-null    float64
 30  cross_track_component         221 non-null    float64
 31  along_track_speed             221 non-null    float64
 32  event_start_hour              221 non-null    int64
 33  event_start_dayofweek         221 non-null    int64
 34  event_start_month             221 non-null    int64
 35  time_to_hit_hours             221 non-null    float64
 36  event                         221 non-null    int64
dtypes: float64(30), int64(7)
memory usage: 64.0 KB

In [9]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   event_id                      95 non-null     int64
 1   num_perimeters_0_5h           95 non-null     int64
 2   dt_first_last_0_5h            95 non-null     float64
 3   low_temporal_resolution_0_5h  95 non-null     int64
 4   area_first_ha                 95 non-null     float64
 5   area_growth_abs_0_5h          95 non-null     float64
 6   area_growth_rel_0_5h          95 non-null     float64
 7   area_growth_rate_ha_per_h     95 non-null     float64
 8   log1p_area_first              95 non-null     float64
 9   log1p_growth                  95 non-null     float64
 10  log_area_ratio_0_5h           95 non-null     float64
 11  relative_growth_0_5h          95 non-null     float64
 12  radial_growth_m               95 non-null     float64
 13  radial_growth_rate_m_per_h    95 non-null     float64
 14  centroid_displacement_m       95 non-null     float64
 15  centroid_speed_m_per_h        95 non-null     float64
 16  spread_bearing_deg            95 non-null     float64
 17  spread_bearing_sin            95 non-null     float64
 18  spread_bearing_cos            95 non-null     float64
 19  dist_min_ci_0_5h              95 non-null     float64
 20  dist_std_ci_0_5h              95 non-null     float64
 21  dist_change_ci_0_5h           95 non-null     float64
 22  dist_slope_ci_0_5h            95 non-null     float64
 23  closing_speed_m_per_h         95 non-null     float64
 24  closing_speed_abs_m_per_h     95 non-null     float64
 25  projected_advance_m           95 non-null     float64
 26  dist_accel_m_per_h2           95 non-null     float64
 27  dist_fit_r2_0_5h              95 non-null     float64
 28  alignment_cos                 95 non-null     float64
 29  alignment_abs                 95 non-null     float64
 30  cross_track_component         95 non-null     float64
 31  along_track_speed             95 non-null     float64
 32  event_start_hour              95 non-null     int64
 33  event_start_dayofweek         95 non-null     int64
 34  event_start_month             95 non-null     int64
dtypes: float64(29), int64(6)
memory usage: 26.1 KB

In [17]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

In [30]:
param_grid = {
    'n_estimators': [400],
    'min_samples_leaf': [2, 3],
    'min_samples_split': [4, 6],
    'max_depth': [4, 8, 10, 14]
}

In [31]:
assert list(X_train.columns) == list(X_test.columns)

In [32]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=400,
    min_samples_split=5,
    min_samples_leaf=2,
    n_jobs=-1,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestClassifier(min_samples_leaf=2, min_samples_split=5,
                       n_estimators=400, n_jobs=-1, random_state=42)

In [33]:
from sklearn.model_selection import GridSearchCV

In [34]:
final_model = GridSearchCV(model,param_grid , cv=3, verbose=2)

In [35]:
final_model.fit(X_train, y_train)

Fitting 3 folds for each of 16 candidates, totalling 48 fits
[CV] END max_depth=4, min_samples_leaf=2, min_samples_split=4, n_estimators=400; total time=   0.3s
[CV] END max_depth=4, min_samples_leaf=2, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=4, min_samples_leaf=2, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=4, min_samples_leaf=2, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=4, min_samples_leaf=2, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=4, min_samples_leaf=2, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=4, min_samples_leaf=3, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=4, min_samples_leaf=3, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=4, min_samples_leaf=3, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=4, min_samples_leaf=3, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=4, min_samples_leaf=3, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=4, min_samples_leaf=3, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=8, min_samples_leaf=2, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=8, min_samples_leaf=2, min_samples_split=4, n_estimators=400; total time=   0.3s
[CV] END max_depth=8, min_samples_leaf=2, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=8, min_samples_leaf=2, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=8, min_samples_leaf=2, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=8, min_samples_leaf=2, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=8, min_samples_leaf=3, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=8, min_samples_leaf=3, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=8, min_samples_leaf=3, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=8, min_samples_leaf=3, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=8, min_samples_leaf=3, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=8, min_samples_leaf=3, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=10, min_samples_leaf=2, min_samples_split=4, n_estimators=400; total time=   0.3s
[CV] END max_depth=10, min_samples_leaf=2, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=10, min_samples_leaf=2, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=10, min_samples_leaf=2, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=10, min_samples_leaf=2, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=10, min_samples_leaf=2, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=10, min_samples_leaf=3, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=10, min_samples_leaf=3, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=10, min_samples_leaf=3, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=10, min_samples_leaf=3, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=10, min_samples_leaf=3, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=10, min_samples_leaf=3, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=14, min_samples_leaf=2, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=14, min_samples_leaf=2, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=14, min_samples_leaf=2, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=14, min_samples_leaf=2, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=14, min_samples_leaf=2, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=14, min_samples_leaf=2, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=14, min_samples_leaf=3, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=14, min_samples_leaf=3, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=14, min_samples_leaf=3, min_samples_split=4, n_estimators=400; total time=   0.2s
[CV] END max_depth=14, min_samples_leaf=3, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=14, min_samples_leaf=3, min_samples_split=6, n_estimators=400; total time=   0.2s
[CV] END max_depth=14, min_samples_leaf=3, min_samples_split=6, n_estimators=400; total time=   0.2s

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [4, 8, 10, 14],
                         'min_samples_leaf': [2, 3],
                         'min_samples_split': [4, 6], 'n_estimators': [400]},
             verbose=2)

In [36]:
base_prob = rf.predict_proba(X_test)[:, 1]

In [37]:
import numpy as np

prob_12h = np.clip(base_prob * 0.6, 0, 1)
prob_24h = np.clip(base_prob * 0.8, 0, 1)
prob_48h = np.clip(base_prob * 1.0, 0, 1)
prob_72h = np.clip(base_prob * 1.2, 0, 1)

In [38]:
final_model.best_params_

{'max_depth': 4,
 'min_samples_leaf': 2,
 'min_samples_split': 6,
 'n_estimators': 400}

In [39]:
df_sub = pd.read_csv('sample_submission.csv')

In [42]:
df_sub = pd.DataFrame({
    'event_id': test_ids,
    'prob_12h': prob_12h,
    'prob_24h': prob_24h,
    'prob_48h': prob_48h,
    'prob_72h': prob_72h
})

df_sub.to_csv('sub_IM_UXXELUC_HETO2.csv', index=False,index_label=False)

In [43]:
df_sub

    event_id  prob_12h  prob_24h  prob_48h  prob_72h
0   10662602  0.061534  0.082046  0.102557  0.123069
1   13353600  0.455001  0.606668  0.758335  0.910002
2   13942327  0.045079  0.060105  0.075131  0.090157
3   16112781  0.495203  0.660270  0.825338  0.990406
4   17132808  0.312673  0.416897  0.521122  0.625346
..       ...       ...       ...       ...       ...
90  94627327  0.165260  0.220347  0.275434  0.330521
91  96570675  0.024681  0.032908  0.041135  0.049362
92  97225766  0.047405  0.063207  0.079009  0.094811
93  98446281  0.130235  0.173647  0.217058  0.260470
94  99649465  0.075818  0.101091  0.126363  0.151636

[95 rows x 5 columns]