In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [3]:
df_train

,model,year,motor_type,running,wheel,color,type,status,motor_volume,price
0,toyota,2022,petrol,3000 km,left,skyblue,sedan,excellent,2.0,24500
1,mercedes-benz,2014,petrol,132000 km,left,black,sedan,excellent,2.0,25500
2,kia,2018,petrol,95000 miles,left,other,sedan,excellent,2.0,11700
3,mercedes-benz,2002,petrol,137000 miles,left,golden,sedan,excellent,3.2,12000
4,mercedes-benz,2017,petrol,130000 km,left,black,sedan,good,2.0,26000
...,...,...,...,...,...,...,...,...,...,...
1637,hyundai,2017,petrol,120000 miles,left,white,sedan,good,2.0,12400
1638,toyota,2014,petrol,170000 km,left,black,sedan,good,2.0,16500
1639,nissan,2018,petrol,68900 miles,left,blue,suv,good,2.0,19500
1640,nissan,2019,petrol,31000 miles,left,black,suv,excellent,2.0,19500
1641,toyota,2022,petrol,20 km,left,white,sedan,excellent,2.0,28500

In [4]:
df_test

,Id,model,year,motor_type,running,wheel,color,type,status,motor_volume
0,0,kia,2020,petrol,24000 km,left,black,sedan,excellent,2.0
1,1,nissan,2017,petrol,85000 miles,left,white,suv,excellent,2.0
2,2,hyundai,2021,petrol,30000 miles,left,white,sedan,excellent,2.0
3,3,kia,2018,petrol,53000 miles,left,silver,sedan,excellent,2.0
4,4,mercedes-benz,2003,petrol,230000 km,left,black,Universal,normal,1.8
...,...,...,...,...,...,...,...,...,...,...
406,406,nissan,2021,petrol,33400 km,left,black,suv,excellent,2.0
407,407,hyundai,2017,petrol,60000 miles,left,other,sedan,excellent,2.0
408,408,mercedes-benz,2012,petrol,218000 km,left,white,sedan,good,2.0
409,409,kia,2020,petrol,40000 miles,left,red,sedan,good,2.0
410,410,hyundai,2017,petrol,120000 miles,left,white,sedan,excellent,2.0

In [5]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1642 entries, 0 to 1641
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         1642 non-null   object
 1   year          1642 non-null   int64
 2   motor_type    1642 non-null   object
 3   running       1642 non-null   object
 4   wheel         1642 non-null   object
 5   color         1642 non-null   object
 6   type          1642 non-null   object
 7   status        1642 non-null   object
 8   motor_volume  1642 non-null   float64
 9   price         1642 non-null   int64
dtypes: float64(1), int64(2), object(7)
memory usage: 128.4+ KB

In [6]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 411 entries, 0 to 410
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            411 non-null    int64
 1   model         411 non-null    object
 2   year          411 non-null    int64
 3   motor_type    411 non-null    object
 4   running       411 non-null    object
 5   wheel         411 non-null    object
 6   color         411 non-null    object
 7   type          411 non-null    object
 8   status        411 non-null    object
 9   motor_volume  411 non-null    float64
dtypes: float64(1), int64(2), object(7)
memory usage: 32.2+ KB

In [7]:
df_test = df_test.drop('Id', axis=1)

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
label = LabelEncoder()

In [10]:
df_train['model'] = label.fit_transform(df_train['model'])
df_test['model'] = label.transform(df_test['model'])

In [11]:
label.classes_

array(['hyundai', 'kia', 'mercedes-benz', 'nissan', 'toyota'],
      dtype=object)

In [12]:
df_train['motor_type'].unique()

array(['petrol', 'gas', 'petrol and gas', 'diesel', 'hybrid'],
      dtype=object)

In [13]:
df_test['motor_type'].unique()

array(['petrol', 'gas', 'petrol and gas'], dtype=object)

In [14]:
df_train['motor_type'] = label.fit_transform(df_train['motor_type'])
df_test['motor_type'] = label.transform(df_test['motor_type'])

In [15]:
df_train['running'] = df_train['running'].apply(lambda x: int(x.split(' ')[0]) if x.split(' ')[-1] == 'km' else int(x.split(' ')[0]) * 1.6)
df_test['running'] = df_test['running'].apply(lambda x: int(x.split(' ')[0]) if x.split(' ')[-1] == 'km' else int(x.split(' ')[0]) * 1.6)

In [16]:
df_train

,model,year,motor_type,running,wheel,color,type,status,motor_volume,price
0,4,2022,3,3000.0,left,skyblue,sedan,excellent,2.0,24500
1,2,2014,3,132000.0,left,black,sedan,excellent,2.0,25500
2,1,2018,3,152000.0,left,other,sedan,excellent,2.0,11700
3,2,2002,3,219200.0,left,golden,sedan,excellent,3.2,12000
4,2,2017,3,130000.0,left,black,sedan,good,2.0,26000
...,...,...,...,...,...,...,...,...,...,...
1637,0,2017,3,192000.0,left,white,sedan,good,2.0,12400
1638,4,2014,3,170000.0,left,black,sedan,good,2.0,16500
1639,3,2018,3,110240.0,left,blue,suv,good,2.0,19500
1640,3,2019,3,49600.0,left,black,suv,excellent,2.0,19500
1641,4,2022,3,20.0,left,white,sedan,excellent,2.0,28500

In [17]:
df_train['wheel'].unique()

array(['left'], dtype=object)

In [18]:
df_test['wheel'].unique()

array(['left', 'right'], dtype=object)

In [19]:
df_test['wheel'].value_counts()

wheel
left     409
right      2
Name: count, dtype: int64

In [20]:
df_train = df_train.drop('wheel', axis=1)
df_test = df_test.drop('wheel', axis=1)

In [21]:
df_train['color'].value_counts()

color
black      541
white      407
silver     223
gray       189
blue       141
red         47
other       30
cherry      20
green       10
brown       10
golden       6
beige        5
orange       5
clove        3
skyblue      2
purple       2
pink         1
Name: count, dtype: int64

In [22]:
df_test['color'].value_counts()

color
black      131
white       96
silver      61
gray        55
blue        30
red         11
other        7
cherry       7
green        5
orange       3
brown        2
skyblue      1
clove        1
beige        1
Name: count, dtype: int64

In [23]:
set(df_test['color']).difference(set(df_train['color']))

set()

In [24]:
set(df_train['color']).difference(set(df_test['color']))

{'golden', 'pink', 'purple'}

In [25]:
df_train['color'] = label.fit_transform(df_train['color'])
df_test['color'] = label.transform(df_test['color'])

In [26]:
set(df_test['type']).difference(set(df_train['type']))

set()

In [27]:
df_train['type'] = label.fit_transform(df_train['type'])
df_test['type'] = label.transform(df_test['type'])

In [28]:
set(df_test['status']).difference(set(df_train['status']))

set()

In [29]:
df_train['status'] = label.fit_transform(df_train['status'])
df_test['status'] = label.transform(df_test['status'])

In [30]:
df_train

,model,year,motor_type,running,color,type,status,motor_volume,price
0,4,2022,3,3000.0,15,5,1,2.0,24500
1,2,2014,3,132000.0,1,5,1,2.0,25500
2,1,2018,3,152000.0,10,5,1,2.0,11700
3,2,2002,3,219200.0,6,5,1,3.2,12000
4,2,2017,3,130000.0,1,5,2,2.0,26000
...,...,...,...,...,...,...,...,...,...
1637,0,2017,3,192000.0,16,5,2,2.0,12400
1638,4,2014,3,170000.0,1,5,2,2.0,16500
1639,3,2018,3,110240.0,2,6,2,2.0,19500
1640,3,2019,3,49600.0,1,6,1,2.0,19500
1641,4,2022,3,20.0,16,5,1,2.0,28500

In [31]:
df_test

     model  year  motor_type   running  color  type  status  motor_volume
0        1  2020           3   24000.0      1     5       1           2.0
1        3  2017           3  136000.0     16     6       1           2.0
2        0  2021           3   48000.0     16     5       1           2.0
3        1  2018           3   84800.0     14     5       1           2.0
4        2  2003           3  230000.0      1     1       4           1.8
..     ...   ...         ...       ...    ...   ...     ...           ...
406      3  2021           3   33400.0      1     6       1           2.0
407      0  2017           3   96000.0     10     5       1           2.0
408      2  2012           3  218000.0     16     5       2           2.0
409      1  2020           3   64000.0     13     5       2           2.0
410      0  2017           3  192000.0     16     5       1           2.0

[411 rows x 8 columns]

In [32]:
X_train = df_train.drop('price', axis=1)
y_train = df_train['price']
X_test = df_test.copy()

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
model = LinearRegression()

In [35]:
model.fit(X_train, y_train)

LinearRegression()

In [36]:
y_pred = model.predict(X_test)

In [37]:
df_sub = pd.read_csv('sample_submission.csv')

In [38]:
df_sub['price'] = y_pred

In [39]:
df_sub.to_csv('sub.csv', index=False, index_label=False)