#

In [1]:
pip install tqdm

Collecting tqdm
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\user\desktop\ml jupyter\venv\lib\site-packages (from tqdm) (0.4.6)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm
Successfully installed tqdm-4.67.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from tqdm import tqdm

In [19]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import re

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "Accept-Language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"
}
categories = {
    0: "https://lenta.ru/rubrics/russia/",
    1: "https://lenta.ru/rubrics/economics/",
    2: "https://lenta.ru/rubrics/forces/",
    3: "https://lenta.ru/rubrics/ussr/",
    4: "https://lenta.ru/rubrics/sport/",
    5: "https://lenta.ru/rubrics/health/",
    6: "https://lenta.ru/rubrics/realty/",
    7: "https://lenta.ru/rubrics/travel/",
    8: "https://lenta.ru/rubrics/science/"
}

url = "https://lenta.ru/rubrics/russia/"

r = requests.get(url, headers=headers)
soup = BeautifulSoup(r.text, "html.parser")

links = soup.select("a[href*='/news/']")

article_links = []
for a in links:
    href = a.get("href")
    if href and re.search(r"/news/\d{4}/\d{2}/\d{2}/", href):

        if href.startswith("/"):
            href = "https://lenta.ru" + href

        article_links.append(href)


article_links = list(set(article_links))
print("Статей найдено:", len(article_links))


def get_article_text(url):
    r = requests.get(url, headers=headers, timeout=5)

    soup = BeautifulSoup(r.text, "html.parser")

    paragraphs = soup.select("div[data-type='text'] p")

    if not paragraphs:
        paragraphs = soup.select("p")

    text = " ".join(p.get_text(" ", strip=True) for p in paragraphs)
    print("LEN:", len(text))
    return text
    
    





data = []
MAX_ARTICLES_PER_CATEGORY = 500

for article_url in article_links[:MAX_ARTICLES_PER_CATEGORY]:
    try:
        text = get_article_text(article_url)
        if len(text) > 50:
            data.append({
                "category": "politics",
                "text": text
            })
        time.sleep(0.5)
    except Exception as e:
        print("Ошибка:", e)

df = pd.DataFrame(data)
print(df.shape)
df.head()

Статей найдено: 68
LEN: 795
LEN: 1133
LEN: 3542
LEN: 849
LEN: 827
LEN: 575
LEN: 741
LEN: 1048
LEN: 1277
LEN: 697
LEN: 714
LEN: 1105
LEN: 604
LEN: 1055
LEN: 807
LEN: 4993
LEN: 1204
LEN: 681
LEN: 736
LEN: 734
LEN: 866
LEN: 1307
LEN: 808
LEN: 614
LEN: 1455
LEN: 768
LEN: 1421
LEN: 844
LEN: 746
LEN: 724
LEN: 1103
LEN: 2751
LEN: 1471
LEN: 1223
LEN: 905
LEN: 3199
LEN: 823
LEN: 761
LEN: 799
LEN: 603
LEN: 625
LEN: 609
LEN: 1174
LEN: 924
LEN: 1250
LEN: 779
LEN: 861
LEN: 1304
LEN: 741
LEN: 1617
LEN: 683
LEN: 838
LEN: 980
LEN: 983
LEN: 817
LEN: 703
LEN: 4105
LEN: 630
LEN: 824
LEN: 857
LEN: 1300
LEN: 846
LEN: 999
LEN: 932
LEN: 656
LEN: 1457
LEN: 1232
LEN: 874
(68, 2)

   category                                               text
0  politics  Реклама Фото: Peter Nicholls / Reuters Професс...
1  politics  Реклама Фото: Денис Воронин / АГН «Москва» Пре...
2  politics  Реклама Фото: Алексей Никольский / РИА Новости...
3  politics  Реклама Фото: Мария Девахина / РИА Новости Деп...
4  politics  Реклама Фото: Nina Liashonok / Reuters У Росси...

In [20]:
data = []

for article_url in article_links[:10]:
    try:
        text = get_article_text(article_url)
        print("URL:", article_url)
        print("Длина текста:", len(text))

        if len(text) > 50:
            data.append({
                "category": "politics",
                "text": text
            })

        time.sleep(0.5)
    except Exception as e:
        print("Ошибка:", e)

df = pd.DataFrame(data)
print("DF shape:", df.shape)
print(df.head())

LEN: 795
URL: https://lenta.ru/news/2026/02/07/v-ssha-zhestko-otvetili-na-slova-starmera-o-rossii/
Длина текста: 795
LEN: 1133
URL: https://lenta.ru/news/2026/02/06/v-kremle-prokommentirovali-pokushenie-na-generala-alekseeva-v-moskve/
Длина текста: 1133
LEN: 3542
URL: https://lenta.ru/news/2026/02/06/v-eisi-nazvali-tsivilizatsionnye-osnovy-i-sotsialnye-aspekty-edinstva-narodov-rossii/
Длина текста: 3542
LEN: 849
URL: https://lenta.ru/news/2026/02/06/deputat-gosdumy-otreagiroval-na-vynesennyy-emu-na-ukraine-prigovor/
Длина текста: 849
LEN: 827
URL: https://lenta.ru/news/2026/02/06/v-rossii-otvetili-na-trebovanie-ukrainy-po-odesse-na-mirnyh-peregovorah/
Длина текста: 827
LEN: 575
URL: https://lenta.ru/news/2026/02/06/v-rossii-sobaka-razorvala-litso-rebenku/
Длина текста: 575
LEN: 741
URL: https://lenta.ru/news/2026/02/07/nazvan-srok-prezentatsii-zakonoproekta-po-ii/
Длина текста: 741
LEN: 1048
URL: https://lenta.ru/news/2026/02/06/iz-groznogo-vyletel-bort-s-gruppoy-podgotovlennyh-v-universitete-putina-boytsov/
Длина текста: 1048
LEN: 1277
URL: https://lenta.ru/news/2026/02/06/vdovu-uchastnika-svo-lishili-vyplat-iz-za-otnosheniy-na-storone/
Длина текста: 1277
LEN: 697
URL: https://lenta.ru/news/2026/02/07/tramp-prokommentiroval-peregovory-s-iranom/
Длина текста: 697
DF shape: (10, 2)
   category                                               text
0  politics  Реклама Фото: Peter Nicholls / Reuters Професс...
1  politics  Реклама Фото: Денис Воронин / АГН «Москва» Пре...
2  politics  Реклама Фото: Алексей Никольский / РИА Новости...
3  politics  Реклама Фото: Мария Девахина / РИА Новости Деп...
4  politics  Реклама Фото: Nina Liashonok / Reuters У Росси...

In [23]:
all_data = []

for category, base_url in categories.items():
    print(f"\nПарсим категорию: {category}")

    article_links = set()   
    for page in range(1, 11):  
        page_url = base_url if page == 1 else f"{base_url}page/{page}/"
        print("Страница:", page_url)

        r = requests.get(page_url, headers=headers)
        soup = BeautifulSoup(r.text, "html.parser")

        links = soup.select("a[href*='/news/']")

        for a in links:
            href = a.get("href")

            if href and re.search(r"/news/\d{4}/\d{2}/\d{2}/", href):
                if href.startswith("/"):
                    href = "https://lenta.ru" + href
                article_links.add(href)

        time.sleep(0.5)

    print("Уникальных статей:", len(article_links))

    for article_url in article_links:
        try:
            text = get_article_text(article_url)

            if len(text) > 50:
                all_data.append({
                    "category": category,
                    "text": text
                })

            time.sleep(0.3)

        except Exception as e:
            print("Ошибка:", e)

Парсим категорию: 0
Страница: https://lenta.ru/rubrics/russia/
Страница: https://lenta.ru/rubrics/russia/page/2/
Страница: https://lenta.ru/rubrics/russia/page/3/
Страница: https://lenta.ru/rubrics/russia/page/4/
Страница: https://lenta.ru/rubrics/russia/page/5/
Страница: https://lenta.ru/rubrics/russia/page/6/
Страница: https://lenta.ru/rubrics/russia/page/7/
Страница: https://lenta.ru/rubrics/russia/page/8/
Страница: https://lenta.ru/rubrics/russia/page/9/
Страница: https://lenta.ru/rubrics/russia/page/10/
Уникальных статей: 68
LEN: 1133
LEN: 3542
LEN: 849
LEN: 827
LEN: 575
LEN: 741
LEN: 1048
LEN: 1277
LEN: 604
LEN: 714
LEN: 692
LEN: 1105
LEN: 1055
LEN: 807
LEN: 4993
LEN: 1204
LEN: 736
LEN: 866
LEN: 1307
LEN: 1455
LEN: 1421
LEN: 768
LEN: 844
LEN: 746
LEN: 724
LEN: 1103
LEN: 1457
LEN: 1211
LEN: 2751
LEN: 1471
LEN: 1223
LEN: 874
LEN: 905
LEN: 3199
LEN: 823
LEN: 761
LEN: 799
LEN: 603
LEN: 625
LEN: 609
LEN: 1174
LEN: 924
LEN: 1250
LEN: 665
LEN: 779
LEN: 741
LEN: 1304
LEN: 1322
LEN: 1617
LEN: 683
LEN: 838
LEN: 980
LEN: 422
LEN: 983
LEN: 817
LEN: 703
LEN: 4105
LEN: 630
LEN: 824
LEN: 857
LEN: 1300
LEN: 846
LEN: 999
LEN: 932
LEN: 656
LEN: 1334
LEN: 1232
LEN: 874

Парсим категорию: 1
Страница: https://lenta.ru/rubrics/economics/
Страница: https://lenta.ru/rubrics/economics/page/2/
Страница: https://lenta.ru/rubrics/economics/page/3/
Страница: https://lenta.ru/rubrics/economics/page/4/
Страница: https://lenta.ru/rubrics/economics/page/5/
Страница: https://lenta.ru/rubrics/economics/page/6/
Страница: https://lenta.ru/rubrics/economics/page/7/
Страница: https://lenta.ru/rubrics/economics/page/8/
Страница: https://lenta.ru/rubrics/economics/page/9/
Страница: https://lenta.ru/rubrics/economics/page/10/
Уникальных статей: 62
LEN: 1599
LEN: 1416
LEN: 966
LEN: 1307
LEN: 1304
LEN: 945
LEN: 651
LEN: 1252
LEN: 698
LEN: 1211
LEN: 1520
LEN: 692
LEN: 1300
LEN: 862
LEN: 942
LEN: 1062
LEN: 2107
LEN: 685
LEN: 1670
LEN: 1264
LEN: 1632
LEN: 1490
LEN: 1325
LEN: 1026
LEN: 1398
LEN: 1388
LEN: 2737
LEN: 1211
LEN: 1732
LEN: 822
LEN: 874
LEN: 1590
LEN: 1896
LEN: 3199
LEN: 1103
LEN: 1154
LEN: 926
LEN: 1278
LEN: 665
LEN: 979
LEN: 1322
LEN: 2009
LEN: 1265
LEN: 863
LEN: 581
LEN: 1885
LEN: 1561
LEN: 761
LEN: 1446
LEN: 1083
LEN: 1195
LEN: 795
LEN: 1384
LEN: 1070
LEN: 811
LEN: 1018
LEN: 1276
LEN: 982
LEN: 981
LEN: 985
LEN: 1334
LEN: 1758

Парсим категорию: 2
Страница: https://lenta.ru/rubrics/forces/
Страница: https://lenta.ru/rubrics/forces/page/2/
Страница: https://lenta.ru/rubrics/forces/page/3/
Страница: https://lenta.ru/rubrics/forces/page/4/
Страница: https://lenta.ru/rubrics/forces/page/5/
Страница: https://lenta.ru/rubrics/forces/page/6/
Страница: https://lenta.ru/rubrics/forces/page/7/
Страница: https://lenta.ru/rubrics/forces/page/8/
Страница: https://lenta.ru/rubrics/forces/page/9/
Страница: https://lenta.ru/rubrics/forces/page/10/
Уникальных статей: 81
LEN: 729
LEN: 857
LEN: 961
LEN: 745
LEN: 1271
LEN: 859
LEN: 611
LEN: 858
LEN: 1542
LEN: 712
LEN: 1061
LEN: 777
LEN: 1031
LEN: 739
LEN: 934
LEN: 1362
LEN: 1366
LEN: 1104
LEN: 1091
LEN: 684
LEN: 927
LEN: 8398
LEN: 1182
LEN: 7468
LEN: 2378
LEN: 1209
LEN: 3199
LEN: 1582
LEN: 1020
LEN: 1322
LEN: 914
LEN: 855
LEN: 1347
LEN: 830
LEN: 906
LEN: 851
LEN: 10348
LEN: 1347
LEN: 1130
LEN: 902
LEN: 1048
LEN: 1115
LEN: 827
LEN: 739
LEN: 671
LEN: 1177
LEN: 834
LEN: 668
LEN: 1091
LEN: 1160
LEN: 10354
LEN: 693
LEN: 1635
LEN: 1253
LEN: 581
LEN: 1719
LEN: 10907
LEN: 883
LEN: 897
LEN: 959
LEN: 1193
LEN: 882
LEN: 1434
LEN: 743
LEN: 1520
LEN: 1211
LEN: 2275
LEN: 874
LEN: 665
LEN: 633
LEN: 958
LEN: 838
LEN: 1023
LEN: 1256
LEN: 990
LEN: 1178
LEN: 915
LEN: 1098
LEN: 779
LEN: 787
LEN: 1334

Парсим категорию: 3
Страница: https://lenta.ru/rubrics/ussr/
Страница: https://lenta.ru/rubrics/ussr/page/2/
Страница: https://lenta.ru/rubrics/ussr/page/3/
Страница: https://lenta.ru/rubrics/ussr/page/4/
Страница: https://lenta.ru/rubrics/ussr/page/5/
Страница: https://lenta.ru/rubrics/ussr/page/6/
Страница: https://lenta.ru/rubrics/ussr/page/7/
Страница: https://lenta.ru/rubrics/ussr/page/8/
Страница: https://lenta.ru/rubrics/ussr/page/9/
Страница: https://lenta.ru/rubrics/ussr/page/10/
Уникальных статей: 74
LEN: 637
LEN: 665
LEN: 961
LEN: 1039
LEN: 561
LEN: 835
LEN: 962
LEN: 1033
LEN: 826
LEN: 882
LEN: 661
LEN: 745
LEN: 470
LEN: 892
LEN: 584
LEN: 1015
LEN: 794
LEN: 760
LEN: 1190
LEN: 825
LEN: 955
LEN: 992
LEN: 845
LEN: 950
LEN: 1211
LEN: 867
LEN: 1091
LEN: 1211
LEN: 803
LEN: 2097
LEN: 874
LEN: 991
LEN: 1116
LEN: 3199
LEN: 998
LEN: 1164
LEN: 1253
LEN: 1110
LEN: 690
LEN: 850
LEN: 828
LEN: 801
LEN: 665
LEN: 1277
LEN: 1322
LEN: 1021
LEN: 646
LEN: 710
LEN: 1343
LEN: 1226
LEN: 891
LEN: 814
LEN: 774
LEN: 1635
LEN: 741
LEN: 581
LEN: 1185
LEN: 1164
LEN: 959
LEN: 905
LEN: 598
LEN: 948
LEN: 1733
LEN: 1256
LEN: 822
LEN: 1582
LEN: 761
LEN: 710
LEN: 814
LEN: 919
LEN: 835
LEN: 752
LEN: 875
LEN: 1334

Парсим категорию: 4
Страница: https://lenta.ru/rubrics/sport/
Страница: https://lenta.ru/rubrics/sport/page/2/
Страница: https://lenta.ru/rubrics/sport/page/3/
Страница: https://lenta.ru/rubrics/sport/page/4/
Страница: https://lenta.ru/rubrics/sport/page/5/
Страница: https://lenta.ru/rubrics/sport/page/6/
Страница: https://lenta.ru/rubrics/sport/page/7/
Страница: https://lenta.ru/rubrics/sport/page/8/
Страница: https://lenta.ru/rubrics/sport/page/9/
Страница: https://lenta.ru/rubrics/sport/page/10/
Уникальных статей: 80
LEN: 850
LEN: 1034
LEN: 750
LEN: 768
LEN: 808
LEN: 734
LEN: 983
LEN: 690
LEN: 966
LEN: 830
LEN: 938
LEN: 1247
LEN: 1112
LEN: 1045
LEN: 810
LEN: 728
LEN: 846
LEN: 1177
LEN: 817
LEN: 847
LEN: 1093
LEN: 942
LEN: 856
LEN: 702
LEN: 3199
LEN: 1048
LEN: 1322
LEN: 919
LEN: 1162
LEN: 807
LEN: 441
LEN: 1285
LEN: 867
LEN: 883
LEN: 655
LEN: 1205
LEN: 724
LEN: 1081
LEN: 649
LEN: 957
LEN: 883
LEN: 956
LEN: 680
LEN: 1028
LEN: 1174
LEN: 877
LEN: 708
LEN: 676
LEN: 792
LEN: 1156
LEN: 830
LEN: 581
LEN: 1038
LEN: 935
LEN: 661
LEN: 675
LEN: 1181
LEN: 1161
LEN: 806
LEN: 1085
LEN: 882
LEN: 812
LEN: 951
LEN: 923
LEN: 1056
LEN: 902
LEN: 1211
LEN: 1442
LEN: 1011
LEN: 874
LEN: 810
LEN: 1146
LEN: 665
LEN: 1047
LEN: 645
LEN: 865
LEN: 927
LEN: 825
LEN: 1123
LEN: 1334

Парсим категорию: 5
Страница: https://lenta.ru/rubrics/health/
Страница: https://lenta.ru/rubrics/health/page/2/
Страница: https://lenta.ru/rubrics/health/page/3/
Страница: https://lenta.ru/rubrics/health/page/4/
Страница: https://lenta.ru/rubrics/health/page/5/
Страница: https://lenta.ru/rubrics/health/page/6/
Страница: https://lenta.ru/rubrics/health/page/7/
Страница: https://lenta.ru/rubrics/health/page/8/
Страница: https://lenta.ru/rubrics/health/page/9/
Страница: https://lenta.ru/rubrics/health/page/10/
Уникальных статей: 0

Парсим категорию: 6
Страница: https://lenta.ru/rubrics/realty/
Страница: https://lenta.ru/rubrics/realty/page/2/
Страница: https://lenta.ru/rubrics/realty/page/3/
Страница: https://lenta.ru/rubrics/realty/page/4/
Страница: https://lenta.ru/rubrics/realty/page/5/
Страница: https://lenta.ru/rubrics/realty/page/6/
Страница: https://lenta.ru/rubrics/realty/page/7/
Страница: https://lenta.ru/rubrics/realty/page/8/
Страница: https://lenta.ru/rubrics/realty/page/9/
Страница: https://lenta.ru/rubrics/realty/page/10/
Уникальных статей: 52
LEN: 1168
LEN: 1273
LEN: 1651
LEN: 1212
LEN: 882
LEN: 1486
LEN: 1771
LEN: 1771
LEN: 1141
LEN: 1494
LEN: 1895
LEN: 1829
LEN: 815
LEN: 1126
LEN: 1837
LEN: 1724
LEN: 1391
LEN: 1405
LEN: 1211
LEN: 2282
LEN: 874
LEN: 1278
LEN: 3199
LEN: 2026
LEN: 1380
LEN: 977
LEN: 665
LEN: 1322
LEN: 3794
LEN: 913
LEN: 1489
LEN: 1200
LEN: 2767
LEN: 3598
LEN: 2877
LEN: 581
LEN: 1169
LEN: 1478
LEN: 1239
LEN: 915
LEN: 1471
LEN: 1592
LEN: 3920
LEN: 3457
LEN: 1054
LEN: 922
LEN: 1957
LEN: 1339
LEN: 1573
LEN: 1797
LEN: 1334
LEN: 1778

Парсим категорию: 7
Страница: https://lenta.ru/rubrics/travel/
Страница: https://lenta.ru/rubrics/travel/page/2/
Страница: https://lenta.ru/rubrics/travel/page/3/
Страница: https://lenta.ru/rubrics/travel/page/4/
Страница: https://lenta.ru/rubrics/travel/page/5/
Страница: https://lenta.ru/rubrics/travel/page/6/
Страница: https://lenta.ru/rubrics/travel/page/7/
Страница: https://lenta.ru/rubrics/travel/page/8/
Страница: https://lenta.ru/rubrics/travel/page/9/
Страница: https://lenta.ru/rubrics/travel/page/10/
Уникальных статей: 77
LEN: 1144
LEN: 1453
LEN: 1293
LEN: 1162
LEN: 794
LEN: 865
LEN: 1183
LEN: 824
LEN: 928
LEN: 966
LEN: 999
LEN: 1630
LEN: 954
LEN: 1082
LEN: 796
LEN: 725
LEN: 1342
LEN: 867
LEN: 838
LEN: 1136
LEN: 3199
LEN: 1357
LEN: 1034
LEN: 1220
LEN: 1161
LEN: 1322
LEN: 1174
LEN: 832
LEN: 862
LEN: 614
LEN: 1097
LEN: 551
LEN: 1127
LEN: 1112
LEN: 1393
LEN: 1674
LEN: 1168
LEN: 679
LEN: 1115
LEN: 707
LEN: 1103
LEN: 791
LEN: 834
LEN: 786
LEN: 1084
LEN: 984
LEN: 581
LEN: 1374
LEN: 1678
LEN: 1169
LEN: 1341
LEN: 912
LEN: 942
LEN: 882
LEN: 1223
LEN: 3741
LEN: 977
LEN: 615
LEN: 1412
LEN: 1211
LEN: 874
LEN: 1616
LEN: 1071
LEN: 1139
LEN: 1245
LEN: 665
LEN: 889
LEN: 877
LEN: 891
LEN: 700
LEN: 622
LEN: 861
LEN: 1329
LEN: 895
LEN: 1193
LEN: 918
LEN: 1334

Парсим категорию: 8
Страница: https://lenta.ru/rubrics/science/
Страница: https://lenta.ru/rubrics/science/page/2/
Страница: https://lenta.ru/rubrics/science/page/3/
Страница: https://lenta.ru/rubrics/science/page/4/
Страница: https://lenta.ru/rubrics/science/page/5/
Страница: https://lenta.ru/rubrics/science/page/6/
Страница: https://lenta.ru/rubrics/science/page/7/
Страница: https://lenta.ru/rubrics/science/page/8/
Страница: https://lenta.ru/rubrics/science/page/9/
Страница: https://lenta.ru/rubrics/science/page/10/
Уникальных статей: 80
LEN: 1553
LEN: 1393
LEN: 1174
LEN: 950
LEN: 888
LEN: 2241
LEN: 1543
LEN: 795
LEN: 1022
LEN: 1510
LEN: 1264
LEN: 1318
LEN: 1300
LEN: 770
LEN: 1799
LEN: 1409
LEN: 1073
LEN: 1308
LEN: 1310
LEN: 1924
LEN: 1780
LEN: 1838
LEN: 1307
LEN: 1485
LEN: 1329
LEN: 756
LEN: 1574
LEN: 1484
LEN: 3199
LEN: 1258
LEN: 975
LEN: 962
LEN: 1518
LEN: 1032
LEN: 827
LEN: 1041
LEN: 1537
LEN: 1362
LEN: 854
LEN: 1563
LEN: 987
LEN: 1612
LEN: 1021
LEN: 1082
LEN: 972
LEN: 1277
LEN: 1174
LEN: 1185
LEN: 1577
LEN: 1654
LEN: 581
LEN: 1847
LEN: 1042
LEN: 1317
LEN: 1199
LEN: 1593
LEN: 460
LEN: 882
LEN: 1469
LEN: 1366
LEN: 1192
LEN: 1483
LEN: 721
LEN: 886
LEN: 1518
LEN: 1409
LEN: 1727
LEN: 874
LEN: 1151
LEN: 665
LEN: 1622
LEN: 717
LEN: 1446
LEN: 1202
LEN: 1211
LEN: 1032
LEN: 1248
LEN: 3329
LEN: 1606
LEN: 1334

In [27]:
df = pd.DataFrame(all_data)
print(df.shape)

df.to_csv("train.csv", index=False)

(574, 2)

In [28]:
df

     category                                               text
0           0  Реклама Фото: Денис Воронин / АГН «Москва» Пре...
1           0  Реклама Фото: Алексей Никольский / РИА Новости...
2           0  Реклама Фото: Мария Девахина / РИА Новости Деп...
3           0  Реклама Фото: Nina Liashonok / Reuters У Росси...
4           0  Реклама Фото: Константин Кокошкин / Коммерсант...
..        ...                                                ...
569         8  Реклама Фото: Владимир Гердо / ТАСС Операторы ...
570         8  Реклама Mbombe. Фото: Wikipedia Бронеавтомобил...
571         8  Реклама Фото: Вячеслав Прокофьев / РИА Новости...
572         8  Реклама Фото: Unsplash Итальянские ученые обна...
573         8  Реклама Фото: Ukrainian Armed Forces / Reuters...

[574 rows x 2 columns]

In [32]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"\bфото\b.*?(?=\.|,|$)", "", text)
    text = re.sub(r"реклама", "", text)
    text=re.sub(r"[^a-zа-яё\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["text"] = df["text"].apply(clean_text)
df = df.drop_duplicates(subset=["text"]).reset_index(drop=True)
df.to_csv(df.to_csv("lenta_news_dataset_clean.csv", index=False)
, index=False)

'category,text\r\n0,которое было совершено в жилом доме на волоколамском шоссе в москве об этом заявил официальный представитель кремля дмитрий песков его комментарий по ситуации приводит тасс пресс секретарь главы государства отметил что спецслужбы делают свое дело песков пожелал скорейшего выздоровления генералу который получил ранения после покушения в следственном комитете россии рассказали что неизвестный несколько раз выстрелил в алексеева в жилом доме на волоколамском шоссе и скрылся соседи пояснили что нападение на генерала произошло на лестничной клетке когда тот выходил из квартиры очевидцы поделились что слышали несколько выстрелов после этого они нашли генерала в крови он был в сознании следователи начали опрашивать свидетелей подъезд жилого дома где произошло покушение сейчас оцеплен владимир алексеев с года занимает пост первого заместителя начальника главного разведывательного управления генерального штаба вооруженных сил россии\r\n0,мероприятие было посвящено началу года единства народов россии старт которому был дан на марафоне россия семья семей в национальном центре россия выступая на открытии марафона президент россии владимир путин подчеркнул исторические основы единства русский народ еще молодой народ пассионарный устремленный в будущее но постепенно на таких же основах складывалась и наша многонациональная страна россия когда в нее вливались разные народы как отметил доцент финансового университета при правительстве россии павел данилин сплоченность о которой говорил президент всегда была отличительной чертой и источником силы россии находящей свое воплощение как во внешней политике так и в нашей повседневной жизни наш суверенитет абсолютная ценность и сегодня у страны есть надежный фундамент чтобы сохранить его благодаря этому россия продолжает оставаться большой и крепкой семьей семей примером согласия для всего мира заявил доцент финансового университета при правительстве россии павел данилин директор департамента политических исследований аналитического центра вциом михаил мамонов привел данные социологии по его словам процент соотечественников гордятся тем что являются гражданами россии на вопрос о том какие ассоциации вызывают слова единство народов россии процентов говорят о сплоченности рассказал социолог руководитель проектов департамента по работе с экспертным сообществом эиси владимир шаповалов раскрыл цивилизационную основу российского единства единство народов россии их дружба являются неотъемлемой частью нашего цивилизационного кода традиционной ценностью общества сформированной многовековой историей уточнил шаповалов герой россии директор департамента государственной политики в сфере воспитания дополнительного образования и детского отдыха минпросвещения россии игорь юргин привел пример подлинного единства запрос на единство поступает от самих людей многие оказывают гуманитарную помощь нашим солдатам на передовой сказал он политолог илья ухов в свою очередь проанализировал утвержденную президентом стратегию государственной национальной политики россии на период до года по его мнению стратегия уделяет много внимания роли русского народа как государствообразующего например прямо указано что доля мероприятий направленных на популяризацию русской культуры в общем количестве этнокультурных мероприятий должно составлять не менее половины от общего объема пояснил ухов в то же время эксперт в сфере межнациональных отношений анвар гаджиев назвал ключевым инструментом сохранения культуры стратегию развития нематериального этнокультурного наследия народов россии до года государственная стратегия направлена на сохранение самого сердца нашей культуры сказок песен и ремесел подчеркнул эксперт президент российской федерации стрельбы из лука зоригто манханов отметил объединяющую силу русского языка русский язык это цементирующий элемент который помог всем народам нашей страны объединиться сказал он павел данилин подводя итоги круглого стола рассказал о гордости соотечественниками которые своими делами творят историю россии это и выдающиеся ученые двигающие вперед прогресс и спортсмены прославляющие страну и наши несгибаемые воины сво и конечно дети наше общее будущее заключил он\r\n0,об этом сообщает риа новости до этого украинская прокуратура сообщила что парламентария заочно приговорили к годам лишения свободы политика для меня это прежде всего позиция выраженная в конкретных поступках считаю что своим приговором украинский суд дал высокую оценку моей политической деятельности и в году в период событий крымской весны и в году сказал бахарев ранее депутат верховной рады нина южанина рассказала что нардепы до сих пор спорят о том кто должен подписывать мирное соглашение по ее словам в киеве прошла панельная дискуссия с главой мид украины андреем сибигой которого несколько раз спросили о том чья подпись должна стоять под документом\r\n0,которыми она не готова поступиться в ходе мирных переговоров по украине среди них искоренение русофобии в киеве так на новое требование киева о статусе одессы ответил российский политолог юрий кот его слова приводит царьград как ранее заявлял тасс источник в переговорной группе по украине киеву важны гарантии что россия не пойдет на одессу должен быть такой механизм который закрепляет примерно такие вещи заявлял собеседник агентства задача настолько ослабить эту угрозу чтобы потом ни наши дети ни наши внуки вновь не проливали кровь на исторической русской земле ответил на ультиматум киева кот ранее зампред комитета госдумы по международным отношениям алексей чепа указал на желание киева сорвать соглашение по украине\r\n0,об этом сообщает telegram канал происшествия пес напал на ребенка когда тот приблизился к его миске животное в это время ело у пострадавшего выявили перелом челюсти разрыва слезных каналов и повреждение век для того чтобы стабилизировать ребенка медикам потребовалась неделя по факту случившегося возбуждено уголовное дело ранее в подмосковье собака породы аляскинский маламут напала на младенца спасти двухмесячного ребенка не удалось\r\n0,такой срок назвало риа новости со ссылкой на аппарат вице премьера дмитрия григоренко законопроект по ии может быть представлен в правительство уже до конца февраля сообщили в аппарате ранее глава совета по правам человека при президенте спч валерий фадеев рассказал что российские общественники провели с западными нейросетями беседу о политике конфликтах в югославии и донбассе и их диалог закончился скандалом по словам правозащитника он и его коллеги были крайне недовольны результатом так как получили абсолютно западный нарратив идеологизированный западный текст\r\n0,об этом сообщил глава чечни рамзан кадыров в telegram по его словам группа собрана из жителей разных регионов россии все они прошли курс боевой и тактической подготовки под руководством опытных инструкторов в российском университете спецназа рус имени президента россии владимира путина для некоторых из них это уже вторая третья а то и четвертая командировка в зону проведения сво мы уважаем и приветствуем выбор каждого из них встать на защиту родины написал кадыров он добавил что из аэропорта борт провожал председатель правительства чечни начальник регионального оперативного штаба сво магомед даудов соратник кадырова пожелал добровольцам успешной реализации поставленных задач и подчеркнул важность их миссии ранее даудов заявил что с начала сво из чечни в зону боевых действий в рамках ротации отправили бойца сейчас на фронте находятся около тысяч из них\r\n0,об этом сообщили в объединенной пресс службе судов российского региона у не вернувшегося с фронта россиянина остались жена и четверо детей как следует из материалов дела мать детей еще при жизни законного мужа была лишена родительских прав и начала сожительствовать с другим мужчиной мать военнослужащего обратилась в суд потребовав лишить невестку выплат по ее словам семьи как таковой уже давно не было а ее сын собирался официально расторгнуть брак но не успел суд пришел к выводу что вступление россиянки в фактические брачные отношения с другим мужчиной в период когда ее супруг был жив а также выраженное супругом намерение о расторжении брака разрывают юридическую связь между бойцом и его официальной супругой вдову участника сво не только лишили выплат но также с нее дополнительно взыскали тысяч рублей в пользу матери военнослужащего на покрытие судебных издержек решение вступило в законную силу ранее сообщалось что в костроме чиновники лишили пенсии родителей попавшего под артобстрел в зоне проведения сво россиянина своих прав им пришлось добиваться в суде\r\n0,переход населенного пункта под российский контроль оценил военкор александр коц в telegram поповка перешла под российский контроль февраля занятие села позволило расширить плацдарм ширина которого уже составляет девять километров указал журналист дальнейшей целью российских войск в сумской области может стать трасса р соединяющая сумы и харьков добавил он всего за минувшую неделю под российский контроль перешло восемь населенных пунктов в зоне проведения спецоперации\r\n0,ру ребенка без сознания нашли возле школы в дзержинском районе волгограда об этом сообщил портал v ru известно что пятиклассник возвращался с занятий и упал с раскатанной горки подробностей о его состоянии на данный момент нет мальчик лежал неподвижно на спине на льду но пар изо рта у него шел сначала вокруг него собрались сотрудники полиции директор школы тоже подходил потом примчала скорая мальчика увезли на носилках рассказал очевидец в этот же день в омске из окна на третьем этаже одной из школ выпал ученик на опубликованном известно что ребенка доставили в реанимацию\r\n0,к по московскому времени февраля над территорией украины зафиксировали беспилотных летательных аппаратов бпла вс россии telegram канал insider ua определил основную цель ночных российских ударов основная цель россиян энергетика западных регионов где в последнее время свет почти не выключали говорится в публикации источник уточняет что российские беспилотники атакуют трипольскую тепловую электростанцию тэс подстанцию кв в киевской области основная масса дронов пришлась на западные регионы республики кроме того в налете задействованы калибры они бьют по городу бурштын в ивано франковской области украины где расположена бурштанская тэс\r\n0,направленных на достижение урегулирования в зоне сво об этом заявил национальной службе новостей депутат госдумы генерал лейтенант виктор соболев по его словам переговорная стратегия киева заключается в выдвижении все новых доводов относительно завершения конфликта это позволит союзникам украины в европе восстановить свой военно промышленный потенциал подчеркнул он нам нужно во всем учитывать наши национальные интересы добавил соболев аналогичную позицию в беседе в лентой ру выразил и зампред комитета госдумы по международным отношениям алексей чепа он считает что и заявления западных политиков и действия командования вооруженных сил украины всу демонстрируют нежелание подписывать мирное соглашение ранее глава оборонного комитета госдумы андрей картаполов оценил масштабы дезертирства в украинской армии по его оценке число оставивших службу солдат всу может достигать одного миллиона при этом киев склонен в разы занижать истинное число дезертиров отметил он\r\n0,об этом заявила заведующая кафедрой русского языка ргпу им а и герцена наталия козловская передает коммерсантъ она отметила в разговоре с ъ что одно это слово было заимствовано относительно недавно из английского языка по мнению козловской слову коуч уже удалось пройти все этапы ассимиляции как пояснила эксперт слово обозначает важное для экономической и социальной жизни явление популярно и имеет множество производных которые зафиксированы в орфографическом академическом ресурсе академос союз профессионалов в сфере развития потенциала человека в прошлом обратился в правительственную комиссию по русскому языку с просьбой включить слова коучинг и коуч в официальные словари русского языка аналогичные просьбы направили в минпросвещения росстандарт и институт русского языка им в в виноградова ранее сообщалось что словом года в русскоязычном сегменте интернета стала аббревиатура нфт\r\n0,возвращенная с украины рассказала что во время оккупации курской области спала на картошке в подвале об этом сообщает тасс мы боялись обстрелов ночевали в подвале мы уходили туда зимой мы одевались брали одеяла и спали на картошке в подвале была картоха мы на нее матрас и спали на ней поделилась россиянка по ее словам в феврале года ее вместе с сожителями вывезли солдаты вооруженных сил украины всу в город сумы там в пункте временного размещения она провела год апреля года глава генштаба вооруженных сил россии валерий герасимов доложил президенту владимиру путину о завершении операции по освобождению курской области от всу оккупация продлилась месяцев и дней\r\n0,это событие организуют министерство культуры российской федерации и фгбук росконцерт международный детский культурный форум стал площадкой для погружения в культуру и искусство обмена идеями между детьми и взрослыми знакомства с единомышленниками и новыми друзьями в нынешнем году форум соберет свыше участников из регионов россии и зарубежных стран на мероприятии будет представлено шесть творческих направлений в течение трех дней пройдет более мероприятий мастер классы встречи дискуссии сессии арт школы лекции концерты экскурсии и многое многое другое самых маленьких начинающих деятелей искусства или ребят которые просто любят театр кино музыку музеи историю изобразительного искусства важно поддержать перезнакомить друг с другом в рамках одного большого мероприятия куда педагоги детских школ искусств преподаватели по актерскому мастерству хореографии приедут из разных регионов страны чтобы общаться и делиться опытом и когда кто нибудь презентуя свое невероятно яркое шоу или присутствуя на каком нибудь кинофестивале или театральной постановке скажет мы познакомились в москве на детском культурном форуме мы будем уверены что наши усилия были не напрасны рассказала министр культуры россии ольга любимова кураторами форума в году станут народный артист россии сергей безруков генеральный директор большого московского государственного цирка на проспекте вернадского народный артист рф эдгард запашный заслуженный артист россии хореограф егор дружинин генеральный продюсер онлайн кинотеатра okko президент и идеолог всероссийского фестиваля детского семейного кино и анимации медвежонок гавриил гордеев генеральный директор государственной третьяковской галереи елена проничева генеральный директор государственной академической капеллы санкт петербурга ольга хомова директор государственного музея истории русской литературы им в и даля дмитрий бак к открытию форума организаторы подготовили специальный подарок для всех юных участников мероприятия сборник сказки детей россии в который вошли волшебные истории написанные сверстниками авторы современных сказок приняли участие в специальном конкурсе который проводился в рамках предыдущего ii международного детского культурного форума в году в конкурсе приняли участие юные писатели из всех уголков россии в адрес оргкомитета конкурса дети прислали сказок экспертная комиссия во главе с литературным критиком директором государственного музея истории российской литературы д п баком определила одного победителя а также выбрала лучшие работы которые вошли в сборник победителем конкурса стала анна сокольцева из калининграда с произведением лекарство из солнца и меда в книге сказки детей россии опубликованы творческие работы начинающих писателей из регионов россии особенностью детского культурного форума стал конкурс детских инициатив в сфере развития культуры и искусства в этом году на специальной сессии ребята предложат идеи по всем направлениям форума музыка хореография театр и цирк кино и анимации музеи и изо литература и журналистика также финалисты выступят с инициативами по развитию культурного сообщества в своем регионе после защиты проектов в завершение сессии будет определен победитель конкурса также в рамках форума пройдет международная сессия культурная дипломатия спикерами выступят юные таланты которые представляют россию на международных конкурсах они расскажут о своем опыте участия в международных проектах объяснят как это способствует личному творческому развитию поделятся историями знакомств и сотрудничества с юными талантами из других стран для участников форума будет организован квиз знание культура семья эта викторина о культурных династиях россии проводится в партнерстве с российским обществом знание в формате классического квиза команда победитель получает призы от знания кроме того состоится интерактивная сессия кураторов культурный поединок она пройдет в формате брейн ринг на сцене будут соревноваться две команды кураторы и участники форума по одному делегату от федеральных округов и новых регионов в рамках форума пройдет стратегическая сессия хакатон посвященный цифровым технологиям и их влиянию на развитие культуры формат хакатона позволит делегатам форума предложить свое видение вопросов культурной политики вечером участников форума ждет культурная программа августа концертная программа российского государственного симфонического оркестра кинематографии при участии лауреатов всероссийского детского музыкального фестиваля посвященного летию со дня рождения е ф гнесиной августа концерт дружбы гала концерт детских коллективов спутников ведущих государственных национальных коллективов с номерами представителей зарубежных стран\r\n0,несмотря на решение врачебной комиссии федерального онкоцентра об этом сообщила дочь пациентки эвелина ангелиди ее рассказ есть в распоряжении ленты ру в своем обращении она указала что у ее летней матери диагностирован рак молочной железы на данный момент заболевание протекает с метастазами в том числе в центральной нервной системе женщина имеет инвалидность первой группы по словам ангелиди в октябре года врачебная комиссия одного из ведущих федеральных онкоцентров назначила для лечения препарат трастузумаб дерукстекан энхерту однако местный онкодиспансер и минздрав владимирской области отказали в его предоставлении дело дошло до суда который января года обязал региональный минздрав немедленно обеспечить пациентку препаратом однако с тех пор на связь с семьей никто так и не вышел мы подали в суд и выиграли но препарат так и не получили добавила собеседница издания ранее сообщалось что минздрав исключил из списка жизненно необходимых лекарств препаратов при этом в него были внесены восемь новых\r\n0,как пишет telegram канал shot местные жители проснулись около от мощных взрывов характерный звук моторов и взрывы звучат в конаковской районе региона кроме того в километрах от твери в стороне поселка редкино началось задымление и произошел пожар по словам местных жителей в ту сторону выехали несколько пожарных расчетов официальной информации о последствиях вражеской атаки и пострадавших пока не было ранее всу атаковали белгородскую область эскадрильей беспилотников самолетного типа которые имеют большой радиус боевого применения над регионом было сбито дронов\r\n0,кадр telegram канал прокуратура чувашии в чувашии глава шемуршинского муниципального округа сергей галкин устроил драку с охотоведом об этом сообщает региональная прокуратура все произошло в здании шемуршинской районной станции по борьбе с болезнями животных чиновник во время собрания устроил скандал с летним охотоведом одного из охотничьих хозяйств республики во время конфликта галкин нанес побои оппоненту приговором суда виновному назначено наказание в виде штрафа в размере тысяч рублей также удовлетворен гражданский иск потерпевшей стороны говорится в сообщении прокуратуры ранее стало известно что первый заместитель губернатора вологодской области ивана иноземцев стал участником пьяной драки в одном из петербургских отелей чиновник вмешался в конфликт чтобы разнять дерущихся однако в итоге сам оказался замешан в ней\r\n0,com продолжающийся в киеве спор касательно того кто должен подписывать мирный договор с россией со стороны украины является дем

In [33]:
df

     category                                               text
0           0  которое было совершено в жилом доме на волокол...
1           0  мероприятие было посвящено началу года единств...
2           0  об этом сообщает риа новости до этого украинск...
3           0  которыми она не готова поступиться в ходе мирн...
4           0  об этом сообщает telegram канал происшествия п...
..        ...                                                ...
518         8  об этом пишет издание daily express по словам ...
519         8  которые позволяют эффективно поражать технику ...
520         8  mbombe который позиционируют как новую разрабо...
521         8  сколтех и рбк сообщили о запуске второго сезон...
522         8  что экстракт цветков мальвы лесной malva sylve...

[523 rows x 2 columns]

In [31]:
df['category'].unique()

array([0, 1, 2, 3, 4, 6, 7, 8])