In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [3]:
df_train.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,RENT,0.0,EDUCATION,B,6000,11.49,0.17,N,14,0
1,1,22,56000,OWN,6.0,MEDICAL,C,4000,13.35,0.07,N,2,0
2,2,29,28800,OWN,8.0,PERSONAL,A,6000,8.90,0.21,N,10,0
3,3,30,70000,RENT,14.0,VENTURE,B,12000,11.11,0.17,N,5,0
4,4,22,60000,RENT,2.0,MEDICAL,A,6000,6.92,0.10,N,3,0

In [4]:
df_test.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,58645,23,69000,RENT,3.0,HOMEIMPROVEMENT,F,25000,15.76,0.36,N,2
1,58646,26,96000,MORTGAGE,6.0,PERSONAL,C,10000,12.68,0.10,Y,4
2,58647,26,30000,RENT,5.0,VENTURE,E,4000,17.19,0.13,Y,2
3,58648,33,50000,RENT,4.0,DEBTCONSOLIDATION,A,7000,8.90,0.14,N,7
4,58649,26,102000,MORTGAGE,8.0,HOMEIMPROVEMENT,D,15000,16.32,0.15,Y,4

In [5]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          58645 non-null  int64
 1   person_age                  58645 non-null  int64
 2   person_income               58645 non-null  int64
 3   person_home_ownership       58645 non-null  object
 4   person_emp_length           58645 non-null  float64
 5   loan_intent                 58645 non-null  object
 6   loan_grade                  58645 non-null  object
 7   loan_amnt                   58645 non-null  int64
 8   loan_int_rate               58645 non-null  float64
 9   loan_percent_income         58645 non-null  float64
 10  cb_person_default_on_file   58645 non-null  object
 11  cb_person_cred_hist_length  58645 non-null  int64
 12  loan_status                 58645 non-null  int64
dtypes: float64(3), int64(6), object(4)
memory usage: 5.8+ MB

In [6]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39098 entries, 0 to 39097
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          39098 non-null  int64
 1   person_age                  39098 non-null  int64
 2   person_income               39098 non-null  int64
 3   person_home_ownership       39098 non-null  object
 4   person_emp_length           39098 non-null  float64
 5   loan_intent                 39098 non-null  object
 6   loan_grade                  39098 non-null  object
 7   loan_amnt                   39098 non-null  int64
 8   loan_int_rate               39098 non-null  float64
 9   loan_percent_income         39098 non-null  float64
 10  cb_person_default_on_file   39098 non-null  object
 11  cb_person_cred_hist_length  39098 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.6+ MB

In [7]:
df_train = df_train.drop('id', axis=1)
df_test = df_test.drop('id', axis=1)

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
set(df_test['person_home_ownership']).difference(set(df_train['person_home_ownership']))

set()

In [10]:
label = LabelEncoder()

In [11]:
df_train['person_home_ownership'] = label.fit_transform(df_train['person_home_ownership'])
df_test['person_home_ownership'] = label.transform(df_test['person_home_ownership'])

In [12]:
set(df_test['loan_intent']).difference(set(df_train['loan_intent']))

set()

In [13]:
df_train['loan_intent'] = label.fit_transform(df_train['loan_intent'])
df_test['loan_intent'] = label.transform(df_test['loan_intent'])

In [14]:
set(df_test['loan_grade']).difference(set(df_train['loan_grade']))

set()

In [15]:
df_train['loan_grade'] = label.fit_transform(df_train['loan_grade'])
df_test['loan_grade'] = label.transform(df_test['loan_grade'])

In [16]:
set(df_test['cb_person_default_on_file']).difference(set(df_train['cb_person_default_on_file']))

set()

In [17]:
df_train['cb_person_default_on_file'] = label.fit_transform(df_train['cb_person_default_on_file'])
df_test['cb_person_default_on_file'] = label.transform(df_test['cb_person_default_on_file'])

In [18]:
X_train = df_train.drop('loan_status', axis=1)
y_train = df_train['loan_status']
X_test = df_test.copy()

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
model = KNeighborsClassifier(n_neighbors=3)

In [21]:
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [22]:
y_pred = model.predict(X_test)

In [23]:
df_sub = pd.read_csv('sample_submission.csv')

In [24]:
df_sub['loan_status'] = y_pred

In [25]:
df_sub.to_csv('sub.csv', index_label=False, index=False)

In [26]:
df_sub

          id  loan_status
0      58645            1
1      58646            0
2      58647            1
3      58648            0
4      58649            0
...      ...          ...
39093  97738            0
39094  97739            0
39095  97740            0
39096  97741            1
39097  97742            1

[39098 rows x 2 columns]