In [62]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [63]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [64]:
df_train

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,RENT,0.0,EDUCATION,B,6000,11.49,0.17,N,14,0
1,1,22,56000,OWN,6.0,MEDICAL,C,4000,13.35,0.07,N,2,0
2,2,29,28800,OWN,8.0,PERSONAL,A,6000,8.90,0.21,N,10,0
3,3,30,70000,RENT,14.0,VENTURE,B,12000,11.11,0.17,N,5,0
4,4,22,60000,RENT,2.0,MEDICAL,A,6000,6.92,0.10,N,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58640,58640,34,120000,MORTGAGE,5.0,EDUCATION,D,25000,15.95,0.21,Y,10,0
58641,58641,28,28800,RENT,0.0,MEDICAL,C,10000,12.73,0.35,N,8,1
58642,58642,23,44000,RENT,7.0,EDUCATION,D,6800,16.00,0.15,N,2,1
58643,58643,22,30000,RENT,2.0,EDUCATION,A,5000,8.90,0.17,N,3,0
58644,58644,31,75000,MORTGAGE,2.0,VENTURE,B,15000,11.11,0.20,N,5,0

In [65]:
df_test

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,58645,23,69000,RENT,3.0,HOMEIMPROVEMENT,F,25000,15.76,0.36,N,2
1,58646,26,96000,MORTGAGE,6.0,PERSONAL,C,10000,12.68,0.10,Y,4
2,58647,26,30000,RENT,5.0,VENTURE,E,4000,17.19,0.13,Y,2
3,58648,33,50000,RENT,4.0,DEBTCONSOLIDATION,A,7000,8.90,0.14,N,7
4,58649,26,102000,MORTGAGE,8.0,HOMEIMPROVEMENT,D,15000,16.32,0.15,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
39093,97738,22,31200,MORTGAGE,2.0,DEBTCONSOLIDATION,B,3000,10.37,0.10,N,4
39094,97739,22,48000,MORTGAGE,6.0,EDUCATION,A,7000,6.03,0.15,N,3
39095,97740,51,60000,MORTGAGE,0.0,PERSONAL,A,15000,7.51,0.25,N,25
39096,97741,22,36000,MORTGAGE,4.0,PERSONAL,D,14000,15.62,0.39,Y,4
39097,97742,31,45000,RENT,6.0,DEBTCONSOLIDATION,B,19450,9.91,0.44,N,9

In [66]:
df_train = df_train.drop('id', axis=1)
df_test = df_test.drop('id', axis=1)

In [67]:
df_train.isna().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
loan_status                   0
dtype: int64

In [68]:
df_test.isna().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [69]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  58645 non-null  int64
 1   person_income               58645 non-null  int64
 2   person_home_ownership       58645 non-null  object
 3   person_emp_length           58645 non-null  float64
 4   loan_intent                 58645 non-null  object
 5   loan_grade                  58645 non-null  object
 6   loan_amnt                   58645 non-null  int64
 7   loan_int_rate               58645 non-null  float64
 8   loan_percent_income         58645 non-null  float64
 9   cb_person_default_on_file   58645 non-null  object
 10  cb_person_cred_hist_length  58645 non-null  int64
 11  loan_status                 58645 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 5.4+ MB

In [70]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [71]:
set(df_test['person_home_ownership']).difference(set(df_train['person_home_ownership']))

set()

In [72]:
df_train['person_home_ownership'] = label.fit_transform(df_train['person_home_ownership'])
df_test['person_home_ownership'] = label.fit_transform(df_test['person_home_ownership'])

In [73]:
set(df_test['loan_intent']).difference(set(df_train['loan_intent']))

set()

In [74]:
df_train['loan_intent'] = label.fit_transform(df_train['loan_intent'])
df_test['loan_intent'] = label.fit_transform(df_test['loan_intent'])

In [75]:
set(df_test['loan_grade']).difference(set(df_train['loan_grade']))

set()

In [76]:
df_train['loan_grade'] = label.fit_transform(df_train['loan_grade'])
df_test['loan_grade'] = label.fit_transform(df_test['loan_grade'])

In [89]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  58645 non-null  int64
 1   person_income               58645 non-null  int64
 2   person_home_ownership       58645 non-null  int64
 3   person_emp_length           58645 non-null  float64
 4   loan_intent                 58645 non-null  int64
 5   loan_grade                  58645 non-null  int64
 6   loan_amnt                   58645 non-null  int64
 7   loan_int_rate               58645 non-null  float64
 8   loan_percent_income         58645 non-null  float64
 9   cb_person_default_on_file   58645 non-null  int64
 10  cb_person_cred_hist_length  58645 non-null  int64
 11  loan_status                 58645 non-null  int64
dtypes: float64(3), int64(9)
memory usage: 5.4 MB

In [78]:
set(df_test['cb_person_default_on_file']).difference(set(df_train['cb_person_default_on_file']))

set()

In [79]:
df_train['cb_person_default_on_file'] = label.fit_transform(df_train['cb_person_default_on_file'])
df_test['cb_person_default_on_file'] = label.fit_transform(df_test['cb_person_default_on_file'])

In [80]:
X_train = df_train.drop('loan_status', axis=1)
y_train = df_train['loan_status']
X_test = df_test.copy()

In [81]:
from sklearn.neighbors import KNeighborsClassifier

In [82]:
model = KNeighborsClassifier(n_neighbors=3)

In [83]:
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [84]:
y_pred = model.predict(X_test)

In [85]:
df_sub = pd.read_csv('sample_submission.csv')

In [86]:
df_sub['loan_status'] = y_pred

In [87]:
df_sub.to_csv('sub.csv',index = False,index_label = False)

In [88]:
df_sub

          id  loan_status
0      58645            1
1      58646            0
2      58647            1
3      58648            0
4      58649            0
...      ...          ...
39093  97738            0
39094  97739            0
39095  97740            0
39096  97741            1
39097  97742            1

[39098 rows x 2 columns]