In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [3]:
df_train.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

In [4]:
df_test.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,188533,Land,Rover LR2 Base,2015,98000,Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Beige,None reported,Yes
1,188534,Land,Rover Defender SE,2020,9142,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Silver,Black,None reported,Yes
2,188535,Ford,Expedition Limited,2022,28121,Gasoline,3.5L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,White,Ebony,None reported,NaN
3,188536,Audi,A6 2.0T Sport,2016,61258,Gasoline,2.0 Liter TFSI,Automatic,Silician Yellow,Black,None reported,NaN
4,188537,Audi,A6 2.0T Premium Plus,2018,59000,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,None reported,Yes

In [5]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  object
 2   model         125690 non-null  object
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     122307 non-null  object
 6   engine        125690 non-null  object
 7   transmission  125690 non-null  object
 8   ext_col       125690 non-null  object
 9   int_col       125690 non-null  object
 10  accident      124058 non-null  object
 11  clean_title   111451 non-null  object
dtypes: int64(3), object(9)
memory usage: 11.5+ MB

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  object
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(4), object(9)
memory usage: 18.7+ MB

In [7]:
df_train = df_train.drop('id', axis=1)
df_test = df_test.drop('id', axis=1)

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
label = LabelEncoder()

In [53]:
missing = X_train.isnull().sum()
print(missing[missing > 0])

Series([], dtype: int64)

In [11]:
set(df_test['brand']).difference(set(df_train['brand']))

set()

In [12]:
df_train['brand'] = label.fit_transform(df_train['brand'])
df_test['brand'] = label.transform(df_test['brand'])

In [13]:
set(df_test['model']).difference(set(df_train['model']))

{'allroad 2.7T'}

In [14]:
modeModel = df_train['model'].mode()[0]
df_test['model'] = df_test['model'].replace('allroad 2.7T', modeModel)

In [15]:
set(df_test['model']).difference(set(df_train['model']))

set()

In [16]:
df_train['model'] = label.fit_transform(df_train['model'])
df_test['model'] = label.transform(df_test['model'])

In [17]:
modeFuelType = df_train['fuel_type'].mode()[0]
df_train['fuel_type'] = df_train['fuel_type'].fillna(modeFuelType)
df_test['fuel_type'] = df_test['fuel_type'].fillna(modeFuelType)

In [18]:
set(df_test['fuel_type']).difference(set(df_train['fuel_type']))

set()

In [19]:
df_train['fuel_type'] = label.fit_transform(df_train['fuel_type'])
df_test['fuel_type'] = label.transform(df_test['fuel_type'])

In [20]:
df_train['hp'] = df_train['engine'].str.extract(r'(\d+\.?\d*)HP').astype(float)
df_test['hp'] = df_test['engine'].str.extract(r'(\d+\.?\d*)HP').astype(float)

In [24]:
hp_median = df_train['hp'].median()
df_train['hp'] = df_train['hp'].fillna(hp_median)
df_test['hp'] = df_test['hp'].fillna(hp_median)

In [21]:
df_train['liters'] = df_train['engine'].str.extract(r'(\d+\.?\d*)L').astype(float)
df_test['liters'] = df_test['engine'].str.extract(r'(\d+\.?\d*)L').astype(float)

In [25]:
liters_median = df_train['liters'].median()
df_train['liters'] = df_train['liters'].fillna(liters_median)
df_test['liters'] = df_test['liters'].fillna(liters_median)

In [22]:
df_train['cylinders'] = df_train['engine'].str.extract(r'(\d+\.?\d*) Cylinder').astype(float)
df_test['cylinders'] = df_test['engine'].str.extract(r'(\d+\.?\d*) Cylinder').astype(float)

In [26]:
cylinders_median = df_train['cylinders'].median()
df_train['cylinders'] = df_train['cylinders'].fillna(cylinders_median)
df_test['cylinders'] = df_test['cylinders'].fillna(cylinders_median)

In [28]:
df_test = df_test.drop('engine', axis=1)
df_train = df_train.drop('engine', axis=1)

In [42]:
df_train.head()

,brand,model,model_year,milage,fuel_type,transmission,ext_col,int_col,accident,clean_title,price,hp,liters,cylinders
0,31,495,2007,213000,2,38,312,71,1,0,4200,172.0,1.6,4.0
1,28,930,2002,143250,2,38,263,10,0,0,4999,252.0,3.9,8.0
2,9,1575,2002,136731,1,38,38,71,1,0,13900,320.0,5.3,8.0
3,16,758,2017,19500,2,49,29,14,1,0,45000,420.0,5.0,8.0
4,36,1077,2021,7388,2,23,29,10,1,0,97500,208.0,2.0,4.0

In [30]:
set(df_test['transmission']).difference(set(df_train['transmission']))

set()

In [31]:
df_train['transmission'] = label.fit_transform(df_train['transmission'])
df_test['transmission'] = label.transform(df_test['transmission'])

In [32]:
set(df_test['ext_col']).difference(set(df_train['ext_col']))

set()

In [33]:
df_train['ext_col'] = label.fit_transform(df_train['ext_col'])
df_test['ext_col'] = label.transform(df_test['ext_col'])

In [34]:
set(df_test['int_col']).difference(set(df_train['int_col']))

set()

In [35]:
df_train['int_col'] = label.fit_transform(df_train['int_col'])
df_test['int_col'] = label.transform(df_test['int_col'])

In [36]:
df_train['accident'] = df_train['accident'].fillna(df_train['accident'].mode()[0])
df_test['accident'] = df_test['accident'].fillna(df_train['accident'].mode()[0])

In [40]:
df_train['accident'] = label.fit_transform(df_train['accident'])
df_test['accident'] = label.transform(df_test['accident'])

In [37]:
df_train['clean_title'] = df_train['clean_title'].fillna(df_train['clean_title'].mode()[0])
df_test['clean_title'] = df_test['clean_title'].fillna(df_train['clean_title'].mode()[0])

In [41]:
df_train['clean_title'] = label.fit_transform(df_train['clean_title'])
df_test['clean_title'] = label.transform(df_test['clean_title'])

In [43]:
X_train = df_train.drop('price', axis=1)
y_train = df_train['price']
X_test = df_test.copy()

In [44]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

In [45]:
poly = PolynomialFeatures()
model = LinearRegression()
pipe = Pipeline([('X', poly), ('y', model)])

In [46]:
params = {
    'X__degree':np.arange(1, 7),
    'X__include_bias':[False]
}

In [47]:
from sklearn.model_selection import GridSearchCV

In [48]:
finalModel = GridSearchCV(pipe, params, cv=2, verbose=2)

In [49]:
finalModel.fit(X_train, y_train)

Fitting 2 folds for each of 6 candidates, totalling 12 fits
[CV] END .................X__degree=1, X__include_bias=False; total time=   0.1s
[CV] END .................X__degree=1, X__include_bias=False; total time=   0.0s
[CV] END .................X__degree=2, X__include_bias=False; total time=   0.9s
[CV] END .................X__degree=2, X__include_bias=False; total time=   0.9s
[CV] END .................X__degree=3, X__include_bias=False; total time=   9.0s
[CV] END .................X__degree=3, X__include_bias=False; total time=   8.5s
[CV] END .................X__degree=4, X__include_bias=False; total time= 1.3min
[CV] END .................X__degree=4, X__include_bias=False; total time= 1.2min
[CV] END .................X__degree=5, X__include_bias=False; total time=14.6min
[CV] END .................X__degree=5, X__include_bias=False; total time=17.9min
[CV] END .................X__degree=6, X__include_bias=False; total time=17.3min
[CV] END .................X__degree=6, X__include_bias=False; total time=23.6min

C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning:
2 fits failed out of a total of 12.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\sklearn\pipeline.py", line 621, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\sklearn\linear_model\_base.py", line 703, in fit
    self.coef_, _, self.rank_, self.singular_ = linalg.lstsq(X, y, cond=cond)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\scipy\_lib\_util.py", line 1233, in wrapper
    return f(*arrays, *other_args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\scipy\linalg\_basic.py", line 1495, in lstsq
    x, s, rank, info = lapack_func(a1, b1, lwork,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy._core._exceptions._ArrayMemoryError: Unable to allocate 19.1 GiB for an array with shape (94266, 27131) and data type float64

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\sklearn\pipeline.py", line 621, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\sklearn\linear_model\_base.py", line 703, in fit
    self.coef_, _, self.rank_, self.singular_ = linalg.lstsq(X, y, cond=cond)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\scipy\_lib\_util.py", line 1233, in wrapper
    return f(*arrays, *other_args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\scipy\linalg\_basic.py", line 1495, in lstsq
    x, s, rank, info = lapack_func(a1, b1, lwork,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy._core._exceptions._ArrayMemoryError: Unable to allocate 19.1 GiB for an array with shape (94267, 27131) and data type float64

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\user\Desktop\ML Python\venv\Lib\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [0.097443   0.11915451 0.1221949  0.11619228 0.11085093        nan]
  warnings.warn(

GridSearchCV(cv=2,
             estimator=Pipeline(steps=[('X', PolynomialFeatures()),
                                       ('y', LinearRegression())]),
             param_grid={'X__degree': array([1, 2, 3, 4, 5, 6]),
                         'X__include_bias': [False]},
             verbose=2)

In [54]:
finalModel.best_score_

np.float64(0.12219490400683602)

In [55]:
finalModel.best_params_

{'X__degree': np.int64(3), 'X__include_bias': False}

In [56]:
y_pred = finalModel.predict(X_test)

In [57]:
df_sub = pd.read_csv('sample_submission.csv')

In [58]:
df_sub['price'] = y_pred

In [59]:
df_sub.to_csv('sub_csv', index_label=False, index=False)