In [163]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [164]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [165]:
df_train

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,188528,Cadillac,Escalade ESV Platinum,2017,49000,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Beige,None reported,Yes,27500
188529,188529,Mercedes-Benz,AMG C 43 AMG C 43 4MATIC,2018,28600,Gasoline,385.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,At least 1 accident or damage reported,Yes,30000
188530,188530,Mercedes-Benz,AMG GLC 63 Base 4MATIC,2021,13650,Gasoline,469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,White,Black,None reported,Yes,86900
188531,188531,Audi,S5 3.0T Prestige,2022,13895,Gasoline,3.0L,1-Speed Automatic,Daytona Gray Pearl Effect,Black,None reported,NaN,84900
188532,188532,Porsche,Macan Base,2016,59500,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Black,None reported,Yes,28995

In [166]:
df_test

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,188533,Land,Rover LR2 Base,2015,98000,Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Beige,None reported,Yes
1,188534,Land,Rover Defender SE,2020,9142,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Silver,Black,None reported,Yes
2,188535,Ford,Expedition Limited,2022,28121,Gasoline,3.5L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,White,Ebony,None reported,NaN
3,188536,Audi,A6 2.0T Sport,2016,61258,Gasoline,2.0 Liter TFSI,Automatic,Silician Yellow,Black,None reported,NaN
4,188537,Audi,A6 2.0T Premium Plus,2018,59000,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,None reported,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
125685,314218,Mercedes-Benz,GL-Class GL 450 4MATIC,2014,83315,Gasoline,362.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Black,None reported,Yes
125686,314219,Audi,Q7 55 Prestige,2019,29336,Gasoline,3.0 Liter Turbo,Automatic,White,Black,None reported,NaN
125687,314220,Audi,A6 3.0T Premium Plus,2012,77634,Gasoline,333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes
125688,314221,Audi,Q7 3.0T Premium,2012,112000,Gasoline,333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes
125689,314222,Chevrolet,Tahoe LT,2018,66840,Gasoline,355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,None reported,Yes

In [167]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  object
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(4), object(9)
memory usage: 18.7+ MB

In [168]:
df_train = df_train.drop('id', axis=1)
df_test = df_test.drop('id', axis=1)

In [198]:
df_train.isna().sum()

brand            0
model            0
model_year       0
milage           0
fuel_type        0
transmission     0
ext_col          0
int_col          0
accident         0
clean_title      0
price            0
hp               0
engine_volume    0
cylinders        0
dtype: int64

In [199]:
df_test.isna().sum()

brand            0
model            0
model_year       0
milage           0
fuel_type        0
transmission     0
ext_col          0
int_col          0
accident         0
clean_title      0
hp               0
engine_volume    0
cylinders        0
dtype: int64

In [171]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

In [172]:
missing = X_train.isnull().sum()
print(missing[missing > 0])

fuel_type       5083
accident        2452
clean_title    21419
dtype: int64

In [173]:
df_train['brand'] = label.fit_transform(df_train['brand'])
df_test['brand'] = label.transform(df_test['brand'])

In [174]:
set(df_test['model']).difference(set(df_train['model']))

{'allroad 2.7T'}

In [175]:
modeModel = df_train['model'].mode()[0]
df_test['model'] = df_test['model'].replace('allroad 2.7T', modeModel)

In [176]:
df_train['model'] = label.fit_transform(df_train['model'])
df_test['model'] = label.transform(df_test['model'])

In [177]:
fuel_probs = df_train['fuel_type'].value_counts(normalize=True)

df_train['fuel_type'] = df_train['fuel_type'].apply(
    lambda x: np.random.choice(fuel_probs.index, p=fuel_probs.values)
    if pd.isna(x) else x
)

df_test['fuel_type'] = df_test['fuel_type'].apply(
    lambda x: np.random.choice(fuel_probs.index, p=fuel_probs.values)
    if pd.isna(x) else x
)

In [178]:
df_train['fuel_type'] = label.fit_transform(df_train['fuel_type'])
df_test['fuel_type'] = label.transform(df_test['fuel_type'])

In [179]:
df_train['hp'] = df_train['engine'].str.extract(r'(\d+\.?\d*)HP').astype(float)
df_test['hp'] = df_test['engine'].str.extract(r'(\d+\.?\d*)HP').astype(float)

In [180]:
df_train['engine_volume'] = df_train['engine'].str.extract(r'(\d+\.?\d*)L').astype(float)
df_test['engine_volume'] = df_test['engine'].str.extract(r'(\d+\.?\d*)L').astype(float)

In [181]:
df_train['cylinders'] = df_train['engine'].str.extract(r'(\d+)\sCylinder').astype(float)
df_test['cylinders'] = df_test['engine'].str.extract(r'(\d+)\sCylinder').astype(float)

In [182]:
df_train = df_train.drop(columns=['engine'])
df_test = df_test.drop(columns=['engine'])

In [200]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   brand          188533 non-null  int64
 1   model          188533 non-null  int64
 2   model_year     188533 non-null  int64
 3   milage         188533 non-null  int64
 4   fuel_type      188533 non-null  int64
 5   transmission   188533 non-null  int64
 6   ext_col        188533 non-null  int64
 7   int_col        188533 non-null  int64
 8   accident       188533 non-null  int64
 9   clean_title    188533 non-null  int64
 10  price          188533 non-null  int64
 11  hp             188533 non-null  int64
 12  engine_volume  188533 non-null  int64
 13  cylinders      188533 non-null  int64
dtypes: int64(14)
memory usage: 20.1 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   brand          125690 non-null  int64
 1   model          125690 non-null  int64
 2   model_year     125690 non-null  int64
 3   milage         125690 non-null  int64
 4   fuel_type      125690 non-null  int64
 5   transmission   125690 non-null  int64
 6   ext_col        125690 non-null  int64
 7   int_col        125690 non-null  int64
 8   accident       125690 non-null  int64
 9   clean_title    125690 non-null  int64
 10  hp             125690 non-null  int64
 11  engine_volume  125690 non-null  int64
 12  cylinders      125690 non-null  int64
dtypes: int64(13)
memory usage: 12.5 MB

In [184]:
df_train['transmission'] = label.fit_transform(df_train['transmission'])
df_test['transmission'] = label.transform(df_test['transmission'])

In [185]:
df_train['ext_col'] = label.fit_transform(df_train['ext_col'])
df_test['ext_col'] = label.transform(df_test['ext_col'])

In [186]:
df_train['int_col'] = label.fit_transform(df_train['int_col'])
df_test['int_col'] = label.transform(df_test['int_col'])

In [187]:
df_train['accident'].value_counts()

accident
None reported                             144514
At least 1 accident or damage reported     41567
Name: count, dtype: int64

In [188]:
df_train['accident'] = df_train['accident'].apply(lambda x: np.random.choice(a=['None reported', 'At least 1 accident or damage reported'], p=[0.7, 0.3]) if pd.isna(x) else x)
df_test['accident'] = df_test['accident'].apply(lambda x: np.random.choice(a=['None reported', 'At least 1 accident or damage reported'], p=[0.7, 0.3]) if pd.isna(x) else x)

In [189]:
df_train['accident'] = label.fit_transform(df_train['accident'])
df_test['accident'] = label.transform(df_test['accident'])

In [190]:
df_train['clean_title'].value_counts()

clean_title
Yes    167114
Name: count, dtype: int64

In [191]:
df_train['clean_title'] = df_train['clean_title'].fillna(df_train['clean_title'].mode()[0])
df_test['clean_title'] = df_test['clean_title'].fillna(df_train['clean_title'].mode()[0])

In [192]:
df_train['clean_title'] = label.fit_transform(df_train['clean_title'])
df_test['clean_title'] = label.transform(df_test['clean_title'])

In [193]:
for col in ['hp', 'engine_volume', 'cylinders']:
    median_value = df_train[col].median()
    df_train[col] = df_train[col].fillna(median_value)
    df_test[col] = df_test[col].fillna(median_value)

In [194]:
df_train['hp'] = label.fit_transform(df_train['hp'])
df_test['hp'] = label.transform(df_test['hp'])

In [195]:
df_train['engine_volume'] = label.fit_transform(df_train['engine_volume'])
df_test['engine_volume'] = label.transform(df_test['engine_volume'])

In [196]:
df_train['cylinders'] = label.fit_transform(df_train['cylinders'])
df_test['cylinders'] = label.transform(df_test['cylinders'])

In [201]:
y_train = df_train['price']
X_train = df_train.drop(columns=['price'])

X_test = df_test.copy()

In [202]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

In [203]:
model = XGBRegressor(
    random_state=42,
    n_jobs=-1
)

In [204]:
params = {
    'model__n_estimators': [500, 800],
    'model__max_depth': [4, 6, 8],
    'model__learning_rate': [0.03, 0.05],
    'model__subsample': [0.8],
    'model__colsample_bytree': [0.8]
}

In [205]:
pipe = Pipeline([('model',model)])

In [206]:
final_model = GridSearchCV(
    pipe,
    params,
    cv=3,
    scoring='neg_root_mean_squared_error',
    verbose=2,
    n_jobs=-1
)

In [207]:
final_model.fit(X_train,y_train)

Fitting 3 folds for each of 12 candidates, totalling 36 fits

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('model',
                                        XGBRegressor(base_score=None,
                                                     booster=None,
                                                     callbacks=None,
                                                     colsample_bylevel=None,
                                                     colsample_bynode=None,
                                                     colsample_bytree=None,
                                                     device=None,
                                                     early_stopping_rounds=None,
                                                     enable_categorical=False,
                                                     eval_metric=None,
                                                     feature_types=None,
                                                     feature_weights=None,
                                                     gamma=None,
                                                     grow_policy=None,
                                                     importance_type=None,
                                                     int...
                                                     min_child_weight=None,
                                                     missing=nan,
                                                     monotone_constraints=None,
                                                     multi_strategy=None,
                                                     n_estimators=None,
                                                     n_jobs=-1,
                                                     num_parallel_tree=None, ...))]),
             n_jobs=-1,
             param_grid={'model__colsample_bytree': [0.8],
                         'model__learning_rate': [0.03, 0.05],
                         'model__max_depth': [4, 6, 8],
                         'model__n_estimators': [500, 800],
                         'model__subsample': [0.8]},
             scoring='neg_root_mean_squared_error', verbose=2)

In [208]:
final_model.best_params_

{'model__colsample_bytree': 0.8,
 'model__learning_rate': 0.03,
 'model__max_depth': 4,
 'model__n_estimators': 500,
 'model__subsample': 0.8}

In [209]:
y_pred = final_model.predict(X_test)

In [210]:
df_sub = pd.read_csv('sample_submission.csv')

In [211]:
df_sub['price'] = y_pred

In [212]:
df_sub.to_csv('sub.csv', index=False, index_label=False)

In [213]:
df_sub

            id         price
0       188533  17061.417969
1       188534  78613.867188
2       188535  54365.968750
3       188536  34178.355469
4       188537  29163.376953
...        ...           ...
125685  314218  30134.173828
125686  314219  46535.937500
125687  314220  26948.990234
125688  314221  18041.722656
125689  314222  37014.664062

[125690 rows x 2 columns]